[WIP]: feat: JavaScript inspector
openkraken/kraken pull request #114
Opened 2021-03-26 07:10 UTC by andycall

2021-03-30 13:12 UTC, yuanyan commented on bridge/devtools/README.md
> +### 介绍
Readme 用英文

2021-03-30 13:14 UTC, andycall commented on bridge/devtools/README.md
> +### 介绍
意外复制进来了，先删掉了

2021-03-31 06:37 UTC, yuanyan commented on bridge/devtools/frontdoor.cc
> +//  if (m_server) {
删除注释

2021-04-02 02:36 UTC, wssgcg1213 requested changes
这部分代码的质量有些差，不符合 Kraken 的代码习惯, 比如
1. 注释应该使用英文, 这里有相当的中文注释
2. 注释代码段应该删除
3. 一些命名空间应该是需要修改的, 比如 KRAKEN_DEBUGGER 后面应该不是这个

而且文件量很大无法 Review, 我建议取消这个 PR, 按功能提交

2021-04-02 09:57 UTC, andycall commented
> 这部分代码的质量有些差，不符合 Kraken 的代码习惯, 比如
> 
> 1. 注释应该使用英文, 这里有相当的中文注释
> 2. 注释代码段应该删除
> 3. 一些命名空间应该是需要修改的, 比如 KRAKEN_DEBUGGER 后面应该不是这个
> 
> 而且文件量很大无法 Review, 我建议取消这个 PR, 按功能提交

迁移的代码

2021-04-02 09:57 UTC, closed without merging