fix: style and script element load order
openkraken/kraken pull request #1155
Opened 2022-02-10 03:49 UTC by wssgcg1213

1. 修复当 style 节点中后插入 TextNode 时，样式不会被重新计算的问题 Close #1154 
2. 修复 script 节点的 src 并没有通过 UriParser 解析 URL 的问题  
  2.1 修复 example 的 bundle.html 示例中外链 script 未加载的问题
3. 适当重构提取了 ScriptElement, StyleElement 中的一些相同逻辑, 保证相同代码仅出现一次
4. 修复 KrakenBundle 加载流程, 明确区分 resolve/eval 两个阶段, 不在 eval 中再调用 resolve

2022-02-10 04:24 UTC, answershuto commented on kraken/lib/src/dom/elements/head.dart
> +      buffer.write(node.data);
两个连续的 TextNode 在 Script 下时，当上一个没有分号结尾时，直接拼接在一起，感觉无法正常 work。

2022-02-10 05:57 UTC, answershuto approved these changes

2022-02-11 08:21 UTC, andycall commented on kraken/lib/src/bridge/to_native.dart
> -  setProperty,
C++ 那边到名字没改

2022-02-11 08:23 UTC, andycall commented on kraken/lib/src/dom/element_view.dart
> -  static Pointer<NativeString> _getStringValueProperty(Element element, String key) {
这个删掉了，那 C++ 那边呢?

2022-02-11 08:29 UTC, wssgcg1213 commented on kraken/lib/src/dom/element_view.dart
> -  static Pointer<NativeString> _getStringValueProperty(Element element, String key) {
你没实现

2022-02-11 08:30 UTC, wssgcg1213 commented on kraken/lib/src/dom/element_view.dart
> -  static Pointer<NativeString> _getStringValueProperty(Element element, String key) {
See element.cc L416-L512

2022-02-11 08:32 UTC, wssgcg1213 commented on kraken/lib/src/dom/element_view.dart
> -  static Pointer<NativeString> _getStringValueProperty(Element element, String key) {
这个 API 是语义不清的, property 可以是任意类型的, attribute 是 string 类型的, 这里原意是去取 attribute 的值, 原先 property 与 attribute 统称 property, 故有这样一个 API. 当前应该通过 target.getAttribute 来获取 String 类型的 attribute, 但是因当下没有这样的用法, 故这里将原先不达意的方法删除

2022-02-11 08:35 UTC, andycall commented on kraken/lib/src/dom/element_view.dart
> -  static Pointer<NativeString> _getStringValueProperty(Element element, String key) {
ok

2022-02-11 09:21 UTC, wssgcg1213 commented on kraken/lib/src/bridge/to_native.dart
> -  setProperty,
DONE

2022-02-15 09:45 UTC, answershuto commented on kraken/lib/src/launcher/controller.dart
> +  Future<KrakenBundle?> get bundle async {
getDefaultBundle?

2022-02-17 10:59 UTC, yuanyan commented on kraken/example/assets/bundle.html
> +        color:red;
color: red;

2022-02-17 11:02 UTC, yuanyan commented on kraken/example/lib/main.dart
> +              _kraken?.redirectTo(KrakenBundle.fromUrl(value));
这里的 _kraken 就是 _webview, 应是 _kraken?.load

2022-02-17 11:28 UTC, yuanyan commented on kraken/lib/src/css/background.dart
> +          uri = controller.uriParser!.resolve(Uri.parse(controller.currentUrl), uri);
controller.currentUrl -》 controller.url

2022-02-17 11:39 UTC, yuanyan commented on kraken/lib/src/devtools/modules/page.dart
> +          'content': (await devtoolsService.controller?.entrypoint)!.content,
webview.getResourceContent()

2022-02-17 11:42 UTC, answershuto commented on kraken/lib/src/dom/element.dart
> +      // @TODO: Parse inline style css text.
style 应该在 C++ 那边有方法处理了吧

2022-02-17 11:42 UTC, answershuto commented on kraken/lib/src/dom/element.dart
> +      // @TODO: Parse inline style css text.
是否需要统一到 Dart 处理。

2022-02-17 11:42 UTC, answershuto commented on kraken/lib/src/launcher/controller.dart
> +  // preload javascript source and cache it.
大写

2022-02-17 11:58 UTC, answershuto commented on kraken/lib/src/dom/text_node.dart
>    String? _data;
是不是可以直接 String _data ，set data 的时候也是可以处理的。

2022-02-17 12:16 UTC, yuanyan commented on kraken/lib/src/devtools/service.dart
> +      String bundleURL = controller.entrypoint?.src ?? '<EmbedBundle>';
webview.url

2022-02-17 13:15 UTC, wssgcg1213 commented on kraken/lib/src/dom/text_node.dart
>    String? _data;
DONE

2022-02-17 13:15 UTC, wssgcg1213 commented on kraken/lib/src/devtools/service.dart
> +      String bundleURL = controller.entrypoint?.src ?? '<EmbedBundle>';
DONE

2022-02-22 07:48 UTC, andycall commented on kraken/lib/src/bridge/from_native.dart
> +getObjectProperty(Object object, String key) {
这部分不是应该在 dom 层处理吗？为啥会出现在 from_native.dart

2022-02-22 07:52 UTC, andycall requested changes

2022-02-22 07:52 UTC, andycall commented on kraken/lib/src/dom/event_target.dart
> +        var result = getObjectProperty(eventTarget, key);
Dart Element 侧的 getProperty 还有承载给用户自定义 Element Property 的能力，getObjectProperty 应当收敛到 Kraken 内置 Element，而不是在通用通道处理

2022-02-23 08:55 UTC, wssgcg1213 commented on kraken/lib/src/bridge/from_native.dart
> +getObjectProperty(Object object, String key) {
分层处理, binding 职责交给 bridge, 所以这里移动过来

2022-02-23 08:55 UTC, wssgcg1213 commented on kraken/lib/src/dom/event_target.dart
> +        var result = getObjectProperty(eventTarget, key);
同上

2022-02-23 11:28 UTC, yuanyan commented on kraken/lib/src/css/overflow.dart
> +import '../../bridge.dart';
import 'package:kraken/bridge.dart';

2022-02-23 11:35 UTC, yuanyan commented on kraken/lib/src/bridge/bindings.dart
> +      case 'scrollLeft': scrollTop = castToType<double>(value); break;
scrollLeft

2022-02-23 11:35 UTC, yuanyan commented on kraken/lib/src/bridge/bindings.dart
> +      case 'offsetTop': return offsetLeft;
offsetTop

2022-02-28 12:52 UTC, yuanyan commented on bridge/bindings/qjs/bom/window.cc
>    return window->callNativeMethods("scroll", 2, arguments);
callNativeMethods 看起来好像是 invokeDartMethod

2022-02-28 12:56 UTC, yuanyan commented on bridge/bindings/qjs/dom/element.cc
> +  return element->getNativeProperty("className");
getNativeProperty -> getBindingProperty

2022-02-28 12:57 UTC, yuanyan commented on bridge/bindings/qjs/dom/element.cc
> +  element->setNativeProperty("className", nativeValue);
setNativeProperty -> setBindingProperty

2022-02-28 12:59 UTC, yuanyan commented on kraken/lib/src/bridge/bridge.dart
> +  BindingObjectBridge.setup();
BindingObjectBridge -> BindingBridge

2022-02-28 13:05 UTC, yuanyan commented on kraken/lib/src/foundation/binding.dart
> +  dynamic getProperty(String key) {}
getProperty -> getBindingProperty

2022-02-28 13:05 UTC, yuanyan commented on kraken/lib/src/foundation/binding.dart
> +  void setProperty(String key, value) {}
setProperty -> setBindingProperty

2022-02-28 13:05 UTC, yuanyan commented on kraken/lib/src/foundation/binding.dart
> +  dynamic invokeMethod(String method, List args) {}
invokeMethod -> invokeBindingMethod

2022-03-03 07:53 UTC, yuanyan commented on kraken/lib/src/dom/elements/a.dart
> +    switch (qualifiedName) {
与 setBindingProperty 里实现冗余了

2022-03-04 04:55 UTC, yuanyan commented on kraken/lib/src/dom/event.dart
> +abstract class EventDispatchController {
EventDispatcher 的概念似乎不太对，参考 https://svelte.dev/tutorial/component-events

2022-03-04 06:22 UTC, wssgcg1213 commented on kraken/lib/src/dom/event.dart
> +abstract class EventDispatchController {
恩, 确实不太好, 我又重构了一下

2022-03-04 09:34 UTC, andycall commented on bridge/bindings/qjs/bom/window.cc
> +  JS_ToFloat64(ctx, &arg0, argv[0]);
为啥不用 jsValueToNativeValue

2022-03-04 09:36 UTC, wssgcg1213 commented on bridge/bindings/qjs/bom/window.cc
> +  JS_ToFloat64(ctx, &arg0, argv[0]);
foo(10)   jsValueToNativeValue (args[0]) 之后到 dart 是 int, foo(10.0) jsValueToNativeValue (args[0]) 之后到 dart 是 double, 类型在声明 binding method 的时候是确定的, 确定输入类型是此声明的职责

2022-03-04 09:38 UTC, wssgcg1213 commented on bridge/bindings/qjs/bom/window.cc
> +  JS_ToFloat64(ctx, &arg0, argv[0]);
generator 里面还有一些没有处理完, 我先在 dart 手动转换并 mark todo 了

2022-03-04 10:47 UTC, andycall commented on kraken/lib/src/launcher/controller.dart
> -    this.bundle,
直接调整 public API 的方式不可取，必须要先 deprcated，然后再删除。现在至少需要保留兼容的版本

2022-03-04 10:59 UTC, andycall commented on kraken/lib/src/bridge/binding.dart
> +    }
unbind 这里没有重置为 null

2022-03-04 13:15 UTC, answershuto commented on kraken/lib/src/css/background.dart
> +          uri = controller.uriParser!.resolve(Uri.parse(controller.url), uri);
这个为啥改成了 url

2022-03-04 13:21 UTC, answershuto commented on kraken/lib/src/css/overflow.dart
> +  void _scrollTo({ double? x, double? y, bool? withAnimation }) {
默认值？

2022-03-04 13:21 UTC, answershuto commented on kraken/lib/src/dom/elements/body.dart
> +    // Event of body should set to document element.
documentElement

2022-03-04 13:21 UTC, answershuto commented on kraken/lib/src/dom/elements/html.dart
> +    addEventListener(EVENT_CLICK, dispatchEvent);
这里的目的是为了让input 的焦点转移生效，不应该 dispatch 出去的。

2022-03-04 13:27 UTC, answershuto commented on kraken/lib/src/dom/element_registry.dart
> +  defineElement(INPUT, (context) => InputElement(context: context));
为什么改得风格不一致了

2022-03-04 13:30 UTC, answershuto requested changes

2022-03-04 13:30 UTC, answershuto commented on kraken/lib/src/dom/elements/html.dart
> +    addEventListener(EVENT_CLICK, dispatchEvent);
注册事件的目的是在 Dart 内部有监听。

2022-03-04 14:20 UTC, yuanyan commented on kraken/lib/src/css/background.dart
> +          uri = controller.uriParser!.resolve(Uri.parse(controller.url), uri);
> 

这是重构，修正到与传统 webview 上的概念

2022-03-04 15:46 UTC, yuanyan commented on kraken/lib/src/bridge/binding.dart
> +  static void markEventAvaiableToDispatch(EventTarget target, String type, bool avaiable) {
引入 avaiable 的参数有些复杂化了，可以暴露两个 api （listenEventTarget\unlistenEventTarget）会更清晰易懂

2022-03-08 03:06 UTC, wssgcg1213 commented on kraken/lib/src/bridge/binding.dart
> +  static void markEventAvaiableToDispatch(EventTarget target, String type, bool avaiable) {
OK

2022-03-08 03:08 UTC, wssgcg1213 commented on kraken/lib/src/rendering/pointer.dart
> +  List<String> events = [];
这里最好是隐藏实现, 暴露接口

2022-03-08 03:09 UTC, wssgcg1213 commented on kraken/lib/src/dom/event_target.dart
> +        renderBoxModel.events.add(eventType);
这一段感觉不太好, 有没有优化思路

2022-03-08 03:10 UTC, wssgcg1213 commented on kraken/lib/src/dom/event_target.dart
> +    if (event.bubbles && this is Node) {
用 override 替代 this is

2022-03-08 03:11 UTC, wssgcg1213 commented on kraken/lib/src/dom/event_target.dart
> +    if (event.bubbles && this is Node) {
去 Node 里覆写 dispatchEvent

2022-03-08 03:13 UTC, wssgcg1213 commented on kraken/lib/src/dom/event.dart
> +  AppearEventType prevAppearState = AppearEventType.none;
内部状态用 `_` 私有避免暴露外部

2022-03-08 03:14 UTC, wssgcg1213 commented on kraken/lib/src/dom/event.dart
> +    GestureEvent(
这里忘记 dispatch 出去了

2022-03-08 09:20 UTC, answershuto commented on kraken/lib/src/dom/event_target.dart
> +    if (event.bubbles && this is Node) {
这里是为了跳过 window，Node 这层是有 dispatchEvent 的

2022-03-10 03:41 UTC, wssgcg1213 commented on kraken/lib/src/dom/node.dart
> -  RenderBox? get renderer => throw FlutterError('This node has no render object implemented.');
这里为何改为了 null, 原意是希望有人实现它, 现在是个抽象类, 只需要删除实现即可达到一样的效果 (IDE 会提示必须实现接口)

2022-03-10 03:43 UTC, wssgcg1213 commented on kraken/lib/src/dom/event_target.dart
> +        if (this is Element && (this as Element).renderBoxModel != null) {
为何不把此段逻辑移动到 Element 的 removeEventListener 方法中?

2022-03-10 03:45 UTC, wssgcg1213 commented on kraken/lib/src/dom/event_target.dart
> +    if (event.bubbles && this is Node) {
没有理解呀, 此段逻辑是 Node 相关的, 那么应该实现在 Node 类中, 而不是在父类中判断自身是否为某个子类的实例

2022-03-10 04:11 UTC, wssgcg1213 commented on kraken/lib/src/dom/event_target.dart
> +    if (event.bubbles && this is Node) {
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/3922719/157586963-500971c3-a27a-4334-b8dd-8a3067b0fb4f.png">

2022-03-10 04:12 UTC, wssgcg1213 commented on kraken/lib/src/dom/event_target.dart
> +    if (event.bubbles && this is Node) {
这里缺失了 get the parent 相关的实现导致的 hack

2022-03-11 02:08 UTC, wssgcg1213 commented on kraken/lib/src/dom/event_target.dart
> -    event.target = this;
这里应该需要修改 currentTarget

2022-03-11 02:12 UTC, wssgcg1213 commented on kraken/lib/src/bridge/binding.dart
> +    }
是指这里需要将 ref 上面的绑定置为 null 吗?

2022-03-11 02:13 UTC, wssgcg1213 commented on kraken/lib/src/css/background.dart
> +          uri = controller.uriParser!.resolve(Uri.parse(controller.url), uri);
终于改成 url 了 :)

2022-03-11 02:14 UTC, wssgcg1213 commented on kraken/lib/src/css/overflow.dart
> +  void _scrollTo({ double? x, double? y, bool? withAnimation }) {
先不动吧, 这里只是改了参数类型

2022-03-11 02:39 UTC, wssgcg1213 commented on kraken/lib/src/dom/elements/html.dart
> +      ownerDocument.dispatchEvent(event);
有了 Tree 概念里面的 parent 之后(在 event_target 里), 这里是不是不需要 hack 了, 直接让 scroll 事件从 html -> document -> window 这样沿着 parent 链冒泡就可以了

2022-03-11 03:24 UTC, wssgcg1213 commented on kraken/lib/src/dom/event_target.dart
> +      // To avoid listen more than once.
这里不能 avoid listen more than once, 不然纯 dart API 会受到影响, 原来的逻辑是正确的, 修改的这个逻辑是 bridge 带来的副作用, 所以需要 bridge 层去消化

2022-03-11 03:30 UTC, wssgcg1213 commented on kraken/lib/src/dom/event_target.dart
> +      addEventsToRenderBoxModel(eventType);
这个抽象还是有点奇怪, 首先应该是  addEvent 单数, 其次 EventTarget 不一定是有 renderBoxModel 的, 比如 document/window, 或者 Text (持有的是 RenderParagraph 不是 RenderBoxModel), 所以得再想一下

2022-03-11 04:01 UTC, answershuto commented on kraken/lib/src/dom/event_target.dart
> +      addEventsToRenderBoxModel(eventType);
TextNode 不需要关心这个事情，因为本身没有事件。上层 window 按照标准中会代理到 documentElement 去做这个事情，Element 本身会有 RO，所以派生自 EventTarget 的两个都有处理。

2022-03-11 04:01 UTC, answershuto commented on kraken/lib/src/dom/event_target.dart
> +      // To avoid listen more than once.
删了

2022-03-14 12:48 UTC, wssgcg1213 commented on bridge/bindings/qjs/dom/event_target.cc
> +    return 1;
这里可以用一个常量替代, 提升阅读性

2022-03-14 13:07 UTC, wssgcg1213 commented on kraken/lib/src/dom/window.dart
>        case EVENT_COLOR_SCHEME_CHANGE:
这里 removeEventListener 里面对事件的处理与 addEventListener 不一致, 应当一致, 按上面的逻辑是对的

2022-03-14 13:10 UTC, wssgcg1213 commented on kraken/lib/src/gesture/gesture_manager.dart
> +import 'package:kraken/src/gesture/pointer.dart' as gesture_pointer;
import 'pointer.dart';

2022-03-14 13:11 UTC, wssgcg1213 commented on kraken/lib/src/gesture/gesture_manager.dart
>        _instance = GestureManager._();
这里看着有点乱, 这样写:

```dart
GestureManager instance = _instance = GestureManager._();

//...
```

2022-03-15 08:23 UTC, answershuto commented on kraken/lib/src/dom/event_target.dart
> -    event.target = this;
这不需要，冒泡时才需要

2022-03-15 11:59 UTC, wssgcg1213 commented on kraken/lib/src/rendering/flow.dart
> +    Function? handleEvent,
这个代码不用了

2022-03-15 12:00 UTC, wssgcg1213 commented on kraken/lib/src/gesture/pointer.dart
> +  void UpdateEventTarget(EventTarget eventTarget) {
mark

2022-03-17 09:08 UTC, wssgcg1213 commented on kraken/lib/src/gesture/swipe.dart
> +const double kSwipeSlop = kTouchSlop * 2.0; // Logical pixels
为什么是 * 2?

2022-03-17 09:18 UTC, wssgcg1213 commented on kraken/lib/src/dom/event_target.dart
> +  List<EventTarget> get eventPath {
https://www.w3.org/TR/uievents/#propagation-path  用这个概念更合适一点

2022-03-17 11:41 UTC, wssgcg1213 commented on kraken/lib/src/gesture/gesture_dispatcher.dart
> +  Touch _toTouch(TouchPoint touchPoint) {
```dart
Touch.fromTouchPoint(TouchPoint touchPoint) {

}
```

2022-03-18 02:34 UTC, answershuto approved these changes

2022-03-18 03:53 UTC, temper357 commented on kraken/lib/src/dom/document.dart
> +  TextNode createTextNode(String data, [context]) {
类型为啥要去掉

2022-03-18 06:09 UTC, temper357 approved these changes

2022-03-18 06:16 UTC, answershuto approved these changes

2022-03-18 06:16 UTC, merged