[WIP] Refactor/image
openkraken/kraken pull request #1226
Opened 2022-03-17 08:57 UTC by wssgcg1213

> Note: should merge #1155 first.

1. ImageElement follow w3c logic

2022-03-28 11:53 UTC, andycall commented on kraken/lib/src/dom/elements/img.dart
> -    if (prevSrc != src) {
诶，重复 src 的判断被删掉了？

2022-03-28 12:58 UTC, wssgcg1213 commented on kraken/lib/src/dom/elements/img.dart
> -    if (prevSrc != src) {
https://html.spec.whatwg.org/multipage/embedded-content.html#dom-img-complete  

> The IDL attribute complete must return true if any of the following conditions is true:
>
> Both the [src](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-src) attribute and the [srcset](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-srcset) attribute are omitted.
> The [srcset](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-srcset) attribute is omitted and the [src](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-src) attribute's value is the empty string.
> The [img](https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element) element's [current request](https://html.spec.whatwg.org/multipage/images.html#current-request)'s [state](https://html.spec.whatwg.org/multipage/images.html#img-req-state) is [completely available](https://html.spec.whatwg.org/multipage/images.html#img-all) and its [pending request](https://html.spec.whatwg.org/multipage/images.html#pending-request) is null.
> The [img](https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element) element's [current request](https://html.spec.whatwg.org/multipage/images.html#current-request)'s [state](https://html.spec.whatwg.org/multipage/images.html#img-req-state) is [broken](https://html.spec.whatwg.org/multipage/images.html#img-error) and its [pending request](https://html.spec.whatwg.org/multipage/images.html#pending-request) is null.


complete 仅与上述 4 种判断相关，与其它状态无关

2022-03-28 15:45 UTC, andycall approved these changes

2022-03-29 02:42 UTC, imsobear approved these changes

2022-03-29 03:00 UTC, temper357 submitted a review, later dismissed

2022-03-29 03:16 UTC, answershuto commented on kraken/lib/src/dom/elements/head.dart
> +  void _fetchAndApplyCSSStyle() async {
load 跟 apply 的职责不应该是在 element 中聚合的。可以看一下 Webkit 的 CachedResourceLoader::requestCSSStyleSheet

2022-03-29 03:16 UTC, answershuto commented on kraken/lib/src/painting/cached_network_image.dart
> +      // @TODO!
这个 TODO 的语气那么重么

2022-03-29 03:16 UTC, answershuto commented on kraken/lib/src/painting/cached_network_image.dart
> +      print('delay $count');
what's this?

2022-03-29 03:16 UTC, answershuto commented on kraken/lib/src/painting/cached_network_image.dart
> +        codec: _loadAsync(key, decode, chunkEvents),
load async 啥

2022-03-29 03:17 UTC, answershuto requested changes

2022-03-29 03:17 UTC, answershuto commented on kraken/lib/src/launcher/controller.dart
> +        // parse html.
111

2022-03-29 06:08 UTC, wssgcg1213 commented on kraken/lib/src/painting/cached_network_image.dart
> +        codec: _loadAsync(key, decode, chunkEvents),
SEE https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/image_provider.dart#L641  
Same as official code style.

2022-03-29 06:11 UTC, wssgcg1213 commented on kraken/lib/src/launcher/controller.dart
> +        // parse html.
什么意思? 这个注释是你加的 https://github.com/openkraken/kraken/commit/14049a718bea21c5ea18912f7cefa498909699d0#diff-f3a84c8e1da5ee1a6ef1ca0b19adfaebcd4eebe14f56eb3071178b7f1f117041R75

2022-03-29 06:14 UTC, wssgcg1213 commented on kraken/lib/src/bridge/to_native.dart
> +int _anonymousScriptEvaluationId = 0;
匿名脚本的执行唯一 ID

2022-03-29 06:17 UTC, wssgcg1213 commented on kraken/lib/src/dom/elements/head.dart
> +  void _fetchAndApplyCSSStyle() async {
CachedResourceLoader 是用来加载资源的，这里不需要单独实现的原因是因为缓存是通过 httpClient 全局生效的。
你的建议是?

2022-03-29 06:17 UTC, wssgcg1213 commented on kraken/lib/src/painting/cached_network_image.dart
> +      // @TODO!
已删除

2022-03-29 06:17 UTC, wssgcg1213 commented on kraken/lib/src/painting/cached_network_image.dart
> +      print('delay $count');
已删除

2022-03-29 06:21 UTC, wssgcg1213 commented on kraken/lib/src/launcher/controller.dart
> +        // parse html.
不过确实没有什么作用, 我删掉吧

2022-03-29 06:39 UTC, answershuto commented on kraken/lib/src/dom/elements/head.dart
> +  void _fetchAndApplyCSSStyle() async {
我觉得 element 的职责是 load 或者说 fetch 某个 loader，比如 CssStyleSheetLoader，它加载（或取缓存）完毕后通知相应的解析器做对应处理，而不是继续在这里取 apply 的操作。

2022-03-29 07:07 UTC, wssgcg1213 commented on kraken/lib/src/dom/elements/head.dart
> +  void _fetchAndApplyCSSStyle() async {
Loader 是加载器, webkit 的源码里有各种 Loader, 比如 CachedResourceLoader   
CachedResourceLoader 获取到的资源实体叫做 CachedResource, 再通过这个静态的 createResource 方法转换为 CachedResourceHandle<CachedResource> https://github.com/WebKit/WebKit/blob/068879898ba2453afafb023b7614d9177c9f302a/Source/WebCore/loader/cache/CachedResourceLoader.cpp#L117

每个 CachedResource 对应一个 CachedResourceClient 来负责消费的操作。https://github.com/WebKit/WebKit/blob/068879898ba2453afafb023b7614d9177c9f302a/Source/WebCore/loader/cache/CachedResource.h#L58

这里对应样式的 CachedResourceHandle 是 [CachedCSSStyleSheet](https://github.com/WebKit/WebKit/blob/068879898ba2453afafb023b7614d9177c9f302a/Source/WebCore/loader/cache/CachedCSSStyleSheet.cpp) 。这个类会驱动 CachedResourceClient 来消费数据。

然后在 HTMLLinkElement.h 的 L105 的 setCSSStyleSheet 方法正是来自于 [CachedStylesheetClient](https://github.com/WebKit/WebKit/blob/068879898ba2453afafb023b7614d9177c9f302a/Source/WebCore/loader/cache/CachedStyleSheetClient.h) 并在对应 .cpp 中完成了解析和加载

<img width="391" alt="image" src="https://user-images.githubusercontent.com/3922719/160553165-17520504-7883-4212-9d24-f1a1716fd9bc.png">

----

对应到这里的实现, 我们没有完全对齐的抽象，KrakenBundle 对应的是 CachedResource, 其不同子类的 resolve 方法覆写对应 ResourceLoader，LinkElement 是 client, 原来是它负责驱动 loader 加载 resource, 现在由于没有 loader 概念, 故直接创建 bundle 再执行解析和加载

2022-03-29 07:29 UTC, answershuto commented on kraken/lib/src/dom/elements/head.dart
> +  void _fetchAndApplyCSSStyle() async {
现在的 KrakenBundle 的职责其实就是 Loader + client  的概念，可以在上面做派生的。

```dart
class CSSStyleSheetBundle extends KrakenBundle {
  void resolve() {
    ///xxx
  }
  
  void eval(){
    /// apply
  }
}
```

2022-03-29 07:45 UTC, wssgcg1213 commented on kraken/lib/src/dom/elements/head.dart
> +  void _fetchAndApplyCSSStyle() async {
这样可能跟我原先的设计有差异了，如果 KrakenBundle 是 Loader + Client, 那么它需要两种组合, 比如
| Loader | Client |
| ---------- | ----------------- |
| FileBundle | StylesheetBundle |
| NetworkBundle | JSBundle |
| AssetsBundle | CSSBundle |
| DataBundle | BytecodeBundle | 

每一个 bundle 实例都需要带有其中一种 loader 类型与其中一种 client 类型, 这会导致动态继承, 或者手写 n*m 个类，所以显然不太合适
-----

我的设计是将 bundle 作为资源实体，其如何被消费是 client 的行为, 从而将 loader 与 client 的行为分开来。浏览器也是这样操作的，差异是 client 通过接口定义了行为, 而这里只是通过 bundle.data 提供数据去消费。

2022-03-29 09:43 UTC, temper357 approved these changes

2022-03-29 09:43 UTC, answershuto approved these changes

2022-03-29 09:43 UTC, merged