feat: suport initEvent and createEvent
openkraken/kraken pull request #131
Opened 2021-03-30 12:51 UTC by answershuto

支持不完整的 createEvent 以及 initEvent，降低 Vue 用户开发成本。

close #130

2021-03-30 12:54 UTC, wssgcg1213 commented on integration_tests/specs/dom/events/event.ts
> +    })
分号

2021-03-30 12:54 UTC, wssgcg1213 commented on integration_tests/specs/dom/events/event.ts
> +    div.addEventListener(type,()=>{
注意语法风格

2021-03-30 12:54 UTC, wssgcg1213 commented on integration_tests/specs/dom/events/event.ts
> +    div.addEventListener('click', ()=> {
注意语法风格

2021-03-30 12:54 UTC, wssgcg1213 commented on integration_tests/specs/dom/events/event.ts
> +    div.style.width ='200px';
注意语法风格

2021-03-30 12:54 UTC, wssgcg1213 commented on integration_tests/specs/dom/events/event.ts
> +    const type = 'customType'
注意语法风格, 分号

2021-03-30 12:55 UTC, wssgcg1213 commented on integration_tests/specs/dom/events/event.ts
> +    const type = 'customType'
事件最好全小写, 遵循 W3C 习惯

2021-03-30 12:57 UTC, wssgcg1213 commented on bridge/bindings/jsc/DOM/document.cc
> +  if (eventType == "Event") {
Event 不等于 CustomEvent, https://developer.mozilla.org/zh-CN/docs/Web/API/Document/createEvent

2021-03-30 12:58 UTC, wssgcg1213 commented on bridge/bindings/jsc/DOM/event.cc
> +  eventInstance->_stopPropagationFlag = true;
为啥要停止 propagation?

2021-03-31 02:10 UTC, wssgcg1213 requested changes
问题还是比较多, 需要再修改一下

2021-04-01 04:13 UTC, andycall commented on bridge/bindings/jsc/DOM/document.cc
> +  if (eventType == "Event") {
![image](https://user-images.githubusercontent.com/4409743/113242211-fecc5400-92e2-11eb-89e2-819fc0f31c9c.png)

2021-04-01 04:13 UTC, andycall commented on bridge/bindings/jsc/DOM/document.cc
> +  if (eventType == "Event") {
看上去逻辑是正确的

2021-04-01 04:14 UTC, andycall approved these changes

2021-04-02 02:31 UTC, wssgcg1213 commented on bridge/bindings/jsc/DOM/document.cc
> +  if (eventType == "Event") {
原来下面创建的是  CustomEvent, 现在已经修改过了

2021-04-02 02:31 UTC, wssgcg1213 approved these changes
LGTM

2021-04-02 02:31 UTC, merged