Add more elements
openkraken/kraken pull request #133
Opened 2021-03-31 10:19 UTC by yuanyan

2021-03-31 12:57 UTC, wssgcg1213 requested changes

2021-03-31 12:57 UTC, wssgcg1213 commented on integration_tests/specs/dom/elements/br.ts
> +fdescribe('br-element', () => {
No `f`

2021-03-31 12:57 UTC, wssgcg1213 commented on kraken/macos/libkraken_jsc.dylib
> +/Users/yuanyan/Kraken/kraken/kraken/macos/../../bridge/build/macos/lib/x86_64/libkraken_jsc.dylib
这个文件不要提交上来

2021-03-31 13:54 UTC, answershuto commented on kraken/lib/src/dom/elements/semantics_text.dart
> +  FONT_FAMILY: 'monospace'
是否应该定义成常量？
const String MONOSPACE = 'monospace';

2021-03-31 13:54 UTC, answershuto commented on kraken/lib/src/dom/elements/object.dart
> +  // }
删除注释

2021-04-01 03:36 UTC, yuanyan commented on kraken/lib/src/dom/elements/semantics_text.dart
> +  FONT_FAMILY: 'monospace'
因为字体，字体无法穷举

2021-04-01 03:56 UTC, wssgcg1213 approved these changes

2021-04-01 03:59 UTC, answershuto approved these changes

2021-04-01 04:03 UTC, andycall approved these changes

2021-04-01 04:16 UTC, merged