[fix] 修改前端kraken.methodChannel.addMethodCallHandler的回调中直接更新data，页面不更新问题。
openkraken/kraken pull request #1382
Opened 2022-05-07 07:22 UTC by yifei8

如以下demo，不添加setTimeout的话nativecallmessage发生更新以后不会触发页面更新:
```javascript
data() {
    return {
      nativecallmessage: "111",
      style,
    };
  },
  methods: {
    addMethodCallHandler() {
      console.error("native call:", "addNativeCallHandler");
      kraken.methodChannel.addMethodCallHandler((method, args) => {
        var _this = this
        setTimeout(() => {
          _this.nativecallmessage = "method->" + method + ", args->" + args;
        }, 10);
        console.log("native call:", this.nativecallmessage);
      });
    },
```

2022-05-07 07:35 UTC, wssgcg1213 commented
看起来是其它地方的问题, 跟 methodChannel 的设计没有关系, 你可以把你的原始问题再描述一下看看

2022-05-07 07:35 UTC, wssgcg1213 requested changes
Not approve.

2022-05-07 07:43 UTC, yuanyan commented
这个看起来是纯js的问题，可能是addMethodCallHandler的context问题，看起来与kraken的机制关系不大

2022-05-07 10:02 UTC, yifei8 commented
> 

不是js问题，前端就是按正常的写法写的，下面是完整页面demo，不加settimeout的话，nativecallmessage更新则不刷新页面。

```javascript
<template>
  <div>
    <img
      :style="style.img"
      alt="Kraken logo"
      src="Http://img.alicdn.com/imgextra/i1/O1CN01CUE2IL1FdAGnYPawX_!!6000000000509-2-tps-350-116.png"
    />
    <div :style="style.button" @click="addMethodCallHandler">
      addNativeCallHandler
    </div>
    <div :style="style.btn_txt">
      {{ nativecallmessage }}
    </div>
  </div>
</template>

<script>
const style = {
  button: {
    padding: "10px 10px",
    border: "1px solid #333333",
    margin: "0px 10px",
  },
  btn_txt: {
    padding: "10px 10px",
    border: "1px solid #ff8a00",
    margin: "0px 10px",
  },
};

export default {
  name: "home",
  components: {},
  data() {
    return {
      nativecallmessage: "111",
      callbackmessage: "",
      style,
    };
  },
  methods: {
    addMethodCallHandler() {
      console.error("native call:", "addNativeCallHandler");
      kraken.methodChannel.addMethodCallHandler((method, args) => {
        var _this = this
        setTimeout(() => {
          _this.nativecallmessage = "method->" + method + ", args->" + args;
        }, 10);
        console.log("native call:", this.nativecallmessage);
      });
    }
  },
};
</script>

```

2022-05-09 03:10 UTC, answershuto commented
看 demo 设置 nativecallmessage 后会触发 setter 进入 Vue 的渲染流程的，methodChannel 只提供一个监听消息的时机，跟时机去渲染页面没有关系的，settimeout 也只会把任务放到 task 中而已。

2022-05-09 03:56 UTC, wssgcg1213 commented
addMethodCallHandler 添加的是一个持续性回调, DEMO 里的例子看起来会不断地添加回调, 看起来使用方式上有一些问题

2022-05-09 07:54 UTC, yifei8 commented
> 看 demo 设置 nativecallmessage 后会触发 setter 进入 Vue 的渲染流程的，methodChannel 只提供一个监听消息的时机，跟时机去渲染页面没有关系的，settimeout 也只会把任务放到 task 中而已。

前半句没问题，触发setter以后理论上应该是会update来刷新界面对不对，实验结果是nativecallmessage的值已更新，但页面并没有得到刷新，我这里面为了解决这个异常现象加了settimeout，放到这个task里面去更新就能正常刷新界面了。demo这么写只是为了表达问题。

2022-05-09 08:13 UTC, yifei8 commented
> addMethodCallHandler 添加的是一个持续性回调, DEMO 里的例子看起来会不断地添加回调, 看起来使用方式上有一些问题

这只是个demo，方create里面去注册结果也是一样的

2022-05-10 03:57 UTC, wssgcg1213 commented
> > 看 demo 设置 nativecallmessage 后会触发 setter 进入 Vue 的渲染流程的，methodChannel 只提供一个监听消息的时机，跟时机去渲染页面没有关系的，settimeout 也只会把任务放到 task 中而已。
> 
> 前半句没问题，触发setter以后理论上应该是会update来刷新界面对不对，实验结果是nativecallmessage的值已更新，但页面并没有得到刷新，我这里面为了解决这个异常现象加了settimeout，放到这个task里面去更新就能正常刷新界面了。demo这么写只是为了表达问题。

所以问题还是回到了为什么加了 setTimeout 可以解决这个异常现象, 而不是这个 hack 加在哪里的问题

2022-05-11 09:01 UTC, yifei8 commented
> > > 看 demo 设置 nativecallmessage 后会触发 setter 进入 Vue 的渲染流程的，methodChannel 只提供一个监听消息的时机，跟时机去渲染页面没有关系的，settimeout 也只会把任务放到 task 中而已。
> > 
> > 
> > 前半句没问题，触发setter以后理论上应该是会update来刷新界面对不对，实验结果是nativecallmessage的值已更新，但页面并没有得到刷新，我这里面为了解决这个异常现象加了settimeout，放到这个task里面去更新就能正常刷新界面了。demo这么写只是为了表达问题。
> 
> 所以问题还是回到了为什么加了 setTimeout 可以解决这个异常现象, 而不是这个 hack 加在哪里的问题

2022-05-11 09:04 UTC, yifei8 commented
> > > > 看 demo 设置 nativecallmessage 后会触发 setter 进入 Vue 的渲染流程的，methodChannel 只提供一个监听消息的时机，跟时机去渲染页面没有关系的，settimeout 也只会把任务放到 task 中而已。
> > > 
> > > 
> > > 前半句没问题，触发setter以后理论上应该是会update来刷新界面对不对，实验结果是nativecallmessage的值已更新，但页面并没有得到刷新，我这里面为了解决这个异常现象加了settimeout，放到这个task里面去更新就能正常刷新界面了。demo这么写只是为了表达问题。
> > 
> > 
> > 所以问题还是回到了为什么加了 setTimeout 可以解决这个异常现象, 而不是这个 hack 加在哪里的问题

是的，这个是个bug，有时间一起看看原因。

2022-06-15 14:25 UTC, closed without merging