Fix/stylesheet load
openkraken/kraken pull request #1441
Opened 2022-07-05 15:30 UTC by andycall

修复通过 link 标签无法加载的 CSS 的问题

2022-07-06 02:30 UTC, answershuto requested changes

2022-07-06 02:30 UTC, answershuto commented on integration_tests/specs/dom/elements/link.ts
> +  fit('should work with remote css', async (done) => {
fit

2022-07-06 06:04 UTC, yifei8 submitted a review, later dismissed

2022-07-07 02:56 UTC, answershuto approved these changes

2022-07-07 06:33 UTC, yifei8 approved these changes

2022-07-07 06:34 UTC, merged