Feat: Add flutter 3.0.4 support
openkraken/kraken pull request #1443
Opened 2022-07-06 12:18 UTC by andycall

flutter 2.10.5 版本的 Layout 存在 bug，在 3.0.4 版本是正常的。
可以跳过 2.10.x 版本，直接升级到 3.x 版本

2022-07-06 23:34 UTC, cnryb submitted a review, later dismissed
LGTM

2022-07-07 02:44 UTC, answershuto approved these changes

2022-07-07 02:45 UTC, answershuto commented
CI 似乎没过，see see @andycall

2022-07-12 06:05 UTC, suyulin approved these changes, later dismissed
LGTM

2022-07-12 06:15 UTC, answershuto requested changes
ci 没过，先别合

2022-07-26 09:26 UTC, suyulin commented on kraken/example/linux/CMakeLists.txt
> +set(KRAKEN_TEST_LIBRARY "${CMAKE_CURRENT_SOURCE_DIR}/../../../bridge/build/linux/lib/libkraken_test.so")
这里可以去掉，GitHub  Action linux 无法编译通过

2022-08-07 05:52 UTC, closed without merging