fix: set percentage fail after element attached
openkraken/kraken pull request #165
Opened 2021-04-19 11:59 UTC by temper357

Closes https://github.com/openkraken/kraken/issues/160

修复 element attach 之后给 style 设置百分比值不生效。对于 element attach 后再设置百分比只需给 RenderBoxModel markNeedsLayout 使其重新 layout 以触发 layout 中的百分比计算逻辑。

2021-04-20 11:24 UTC, yuanyan approved these changes

2021-04-21 08:44 UTC, yuanyan requested changes
需要 merge 下 main

2021-04-21 13:38 UTC, wssgcg1213 approved these changes

2021-04-26 03:08 UTC, temper357 commented
重构 constraints 后修改百分比 padding test 跑不过，此 PR 先 hold，待合并 https://github.com/openkraken/kraken/pull/224 后再改。

2021-05-12 09:58 UTC, temper357 commented
padding test 跑不过已经修复了，可以 review 了。

2021-05-13 12:45 UTC, yuanyan approved these changes

2021-05-17 03:15 UTC, wssgcg1213 approved these changes

2021-05-17 03:16 UTC, merged