fix: transform functions split error when more than one.
openkraken/kraken pull request #196
Opened 2021-04-22 10:05 UTC by willgos

transform的function参数大于1个的时候，从第二个function解析开始会把分隔符号“,”带入到function name前，导致无法判断能找到对应的function name，只有一个function生效。
例如：
原始数据：[transform, rotate(23.763669282286536deg) translateX(69.89314494790158px)]
解析过程中会在translateX前加入分隔符号“,”，变成：[transform, rotate(23.763669282286536deg),translateX(69.89314494790158px)]，解析后第二个function name变成：,translateX，导致无法识别。

2021-04-22 10:12 UTC, wssgcg1213 requested changes
需要提供测试用例, 参考 https://openkraken.com/guide/contribute/test

2021-04-22 10:12 UTC, wssgcg1213 commented on kraken/lib/src/css/values/function.dart
> +const String FUNCTION_ARGS_SPLIT = ',';
是这个意思吗? `'\',\''`

2021-04-22 10:14 UTC, andycall requested changes

2021-04-22 10:14 UTC, andycall commented on kraken/lib/src/css/values/function.dart
> +const String FUNCTION_SPLIT = ',';
最好符合其他代码的命名风格：
```dart
final _function_split = ',';
final _function_args_split = ',';
```

2021-04-22 12:56 UTC, andycall commented
@wssgcg1213 貌似第三方 fork 的仓库没有执行 actions 测试

2021-04-22 12:57 UTC, willgos commented on kraken/lib/src/css/values/function.dart
> +const String FUNCTION_SPLIT = ',';
因有两个地方用到：function.dart里static bool isFunction(String value)中（解析使用），sty_declaration.dart里String _normalizeValue(value)中（插入做分隔）；之前直接用 ’,‘ 做插入分隔和解析判断，所以现在把这个分隔符逗号定义成public常量放在了function.dart这边。

2021-04-22 12:57 UTC, willgos commented on kraken/lib/src/css/values/function.dart
> +const String FUNCTION_ARGS_SPLIT = ',';
已经添加了一个简单的测试用例：integration_tests/specs/css/css-transforms/scale_rotate.ts。
另外：integration_tests/specs/css/css-transforms/scale3d.ts 这个测试用例中rotate3d(5deg, 8deg, 3deg)参数有误，不然是可以测试出这个PR场景的。

2021-04-22 13:05 UTC, andycall commented
@willgos 之前 github actions 配置里面没有针对第三方 pull request 启动集成，现在刚修复了这个问题。

你得需要同步一下 main 分支的代码，然后再更新一下这个 pull request

2021-04-22 13:06 UTC, andycall commented
先等一下，貌似配置还有问题。我先看下

2021-04-22 13:46 UTC, andycall commented
@willgos 可以同步 main 分支了，同步之后，应该会自动触发一次集成测试的执行

2021-04-23 01:30 UTC, willgos commented
@andycall 已经同步了main分支。我本地跑了下测试用例，已经跑完更新了。

2021-04-23 01:38 UTC, willgos commented
![image](https://user-images.githubusercontent.com/6659197/115805440-92430180-a417-11eb-8317-5e9c4d9c115d.png)

2021-04-23 04:20 UTC, andycall requested changes

2021-04-23 04:20 UTC, andycall commented on kraken/macos/libkraken_jsc.dylib
> +/Users/shishenglong/workspace/third/kraken/kraken/macos/../../bridge/build/macos/lib/x86_64/libkraken_jsc.dylib
这个文件不要提交

2021-04-23 04:22 UTC, andycall commented
![image](https://user-images.githubusercontent.com/4409743/115817957-5c5d4780-a42e-11eb-9ccb-ac93254e613b.png)

距离合入还差个快速的截图，在 CI 日志里面有快照文件的下载链接。在里面找到你的测试快照图片，然后也提交上来

2021-04-23 05:49 UTC, willgos commented on kraken/macos/libkraken_jsc.dylib
> +/Users/shishenglong/workspace/third/kraken/kraken/macos/../../bridge/build/macos/lib/x86_64/libkraken_jsc.dylib
收到

2021-04-23 06:00 UTC, andycall requested changes

2021-04-23 06:00 UTC, andycall commented on kraken/macos/libkraken_jsc.dylib
> -../../bridge/build/macos/lib/x86_64/libkraken_jsc.dylib
也不要删除，把它从提交历史中忽略掉

2021-04-23 06:00 UTC, willgos commented on kraken/macos/libkraken_jsc.dylib
> -../../bridge/build/macos/lib/x86_64/libkraken_jsc.dylib
好的

2021-04-23 06:40 UTC, andycall approved these changes

2021-04-23 06:57 UTC, andycall commented
@willgos 
![image](https://user-images.githubusercontent.com/4409743/115831511-43f82780-a444-11eb-8b65-93268e128267.png)

lint 挂了

2021-04-24 18:48 UTC, andycall approved these changes

2021-04-25 13:53 UTC, wssgcg1213 approved these changes

2021-04-25 13:53 UTC, merged