Feat/support mouse event
openkraken/kraken pull request #220
Opened 2021-04-25 10:02 UTC by answershuto

支持 mouse event 事件，click 等事件可以返回坐标

close #166

2021-04-28 02:56 UTC, andycall requested changes

2021-04-28 02:56 UTC, andycall commented on bridge/bindings/jsc/DOM/mouse_event.cc
> +    if (property == JSMouseEvent::MouseEventProperty::clientX) {
用 switch case 比较好

2021-04-28 14:06 UTC, andycall submitted a review, later dismissed

2021-04-29 02:37 UTC, wssgcg1213 commented on kraken/lib/src/dom/event_handler.dart
> +    Offset globalOffset = (elementManager.getRootElement().renderBoxModel).globalToLocal(Offset(down.position.dx, down.position.dy));
多了括号  
另外这个有点长, 分开来语义上更好一点

2021-04-29 02:37 UTC, wssgcg1213 commented on kraken/lib/src/dom/event_handler.dart
> +  void dispatchClick(Event event) {
dispatchClick 和 dispatchEvent 的区别是什么? 看上去没有意义

2021-04-29 02:39 UTC, answershuto commented on kraken/lib/src/dom/event_handler.dart
> +  void dispatchClick(Event event) {
dispatchClick 会被 a 标签等点击时候打开 URL 用到，以及 element.click() 方法

2021-04-29 02:45 UTC, wssgcg1213 commented on kraken/lib/src/dom/elements/a.dart
> +    super.dispatchClick(event);
这个地方有点不太对劲

2021-05-06 11:24 UTC, wssgcg1213 commented on kraken/lib/src/dom/elements/a.dart
> +  void dispatchClick(Event event) {
这里命名有问题

2021-05-06 11:24 UTC, wssgcg1213 commented on kraken/lib/src/dom/event_handler.dart
> +import 'package:flutter/material.dart';
不应该在这里依赖 widgets

2021-05-06 11:26 UTC, wssgcg1213 commented on kraken/lib/src/gesture/click.dart
> +      onClick(EVENT_CLICK, down);
这里的参数传递没有看懂, onClick 是一个 ClickEventHandler, 所以原来传入一个 Event 对象是对的, 现在传入的是 type 和一个 PointerDownEvent(RawEvent), 不太合适

2021-05-06 11:29 UTC, wssgcg1213 requested changes
需要再讨论一下

2021-05-07 09:18 UTC, wssgcg1213 commented on kraken/lib/src/gesture/click.dart
> +      onClick(EVENT_CANCEL, down: down );
多了个空格

2021-05-07 09:20 UTC, wssgcg1213 commented on kraken/lib/src/dom/event_handler.dart
> +  void handleMouseClick(String eventType, { PointerDownEvent down, PointerUpEvent up }) {
handleMouseEvent?

2021-05-07 09:21 UTC, wssgcg1213 commented on kraken/lib/src/dom/elements/a.dart
> +  void handleMouseClick(String eventType, { PointerDownEvent down, PointerUpEvent up }) {
handleMouseEvent

2021-05-07 09:21 UTC, wssgcg1213 commented on kraken/lib/src/rendering/pointer.dart
> +typedef ClickEventListener = void Function(String, { PointerDownEvent down, PointerUpEvent up });
MouseEventListener

2021-05-07 09:37 UTC, wssgcg1213 submitted a review, later dismissed

2021-05-07 09:45 UTC, andycall submitted a review, later dismissed

2021-05-07 10:04 UTC, wssgcg1213 approved these changes

2021-05-07 10:23 UTC, wssgcg1213 approved these changes

2021-05-07 10:23 UTC, merged