feat: add script element
openkraken/kraken pull request #221
Opened 2021-04-25 16:03 UTC by yuanyan

1. 新增加了 script 与 head、html
2. 跟节点与浏览器一致为 html, 即 document.documentElement
3. 重构了测试用例流程，去掉了 refreshPaint，当前所有测试用例已经打包为一个 bundle，不再有必要刷新，而且不刷新有机会发现更多问题

2021-04-26 06:56 UTC, answershuto commented on integration_tests/runtime/reset.ts
> +document.documentElement.style.backgroundColor = 'white';
文件末尾空一行

2021-04-26 09:04 UTC, andycall requested changes

2021-04-26 09:04 UTC, andycall commented on kraken/lib/src/css/overflow.dart
> -    elementManager.setEventTarget(scrollingElement);
为啥要把这行删了，删了那上面不就没用了吗？

2021-04-26 09:08 UTC, andycall requested changes

2021-04-26 09:08 UTC, andycall commented on kraken/lib/src/module/performance_timing.dart
> -final String PERF_BODY_ELEMENT_INIT_START = 'body_element_init_start';
PERF 的 Key 删了的话，C++ 那层也要同步修改

https://github.com/openkraken/kraken/blob/main/bridge/bindings/jsc/KOM/performance.h#L62

2021-04-26 09:08 UTC, answershuto submitted a review, later dismissed

2021-04-26 09:11 UTC, andycall requested changes

2021-04-26 09:11 UTC, andycall commented on integration_tests/specs/dom/elements/script.ts
> +fdescribe('script element', () => {
fdescript -> descript

2021-04-26 09:15 UTC, andycall commented
测试现在只跑了1一个，还得先把 fdescript 去掉再看是否测试失败了

2021-04-26 09:15 UTC, andycall commented on bridge/bindings/jsc/DOM/document.cc
> +  case DocumentProperty::documentElement: {
现在这里改了，需要补充一下 `document.body` 和  `document.documentElement` 这两个 API 的单元测试

2021-04-26 09:15 UTC, yuanyan commented on kraken/lib/src/css/overflow.dart
> -    elementManager.setEventTarget(scrollingElement);
没有看懂 scrollingElement 被 js 层引用，理论上没有必要存储在 elementManager 上了

2021-04-26 09:20 UTC, andycall commented on kraken/lib/src/css/overflow.dart
> -    elementManager.setEventTarget(scrollingElement);
scrollingElement 是不会被 JS 引用的，当时有这个代码是因为要创建双层 repaintBoundary 来实现滚动，而 rendering 层每个 RenderObject 强依赖一个 Element 来进行布局，所以才搞出这么 hack 的代码。
@temper357 是不是 rendering 层去掉 targetId 已经搞完了

2021-04-26 09:21 UTC, temper357 commented on bridge/polyfill/src/dom.ts
> +});
polyfill 中是不是要把 <script> 也加上

2021-04-26 09:22 UTC, temper357 commented on kraken/lib/src/css/overflow.dart
> -    elementManager.setEventTarget(scrollingElement);
@andycall 去除 targetId 还没开始搞

2021-04-26 09:37 UTC, wssgcg1213 commented on bridge/polyfill/src/dom.ts
> +});
不需要吧？

2021-04-26 09:45 UTC, yuanyan commented on kraken/lib/src/css/overflow.dart
> -    elementManager.setEventTarget(scrollingElement);
> scrollingElement 是不会被 JS 引用的，当时有这个代码是因为要创建双层 repaintBoundary 来实现滚动，而 rendering 层每个 RenderObject 强依赖一个 Element 来进行布局，所以才搞出这么 hack 的代码。
> @temper357 是不是 rendering 层去掉 targetId 已经搞完了

没有看到有地方通过 tragetId 去读 scrollingElement

2021-04-26 09:53 UTC, wssgcg1213 reviewed
一些细节，大体逻辑上没有问题

2021-04-26 09:53 UTC, wssgcg1213 commented on bridge/polyfill/src/kraken.ts
> +import {dispatchWebSocketEvent} from "./websocket";
这里格式不太统一

2021-04-26 09:53 UTC, wssgcg1213 commented on bridge/polyfill/src/websocket.ts
> +import { initPropertyHandlersForEventTargets } from './helpers';
helper 是个啥啊，感觉不是一个好概念，之前啥时候混进来的

2021-04-26 09:53 UTC, wssgcg1213 commented on integration_tests/assets/hello.js
> +document.body.appendChild(document.createTextNode('Hello'));
这个文件的意义是？

2021-04-26 09:53 UTC, wssgcg1213 commented on kraken/lib/src/dom/document.dart
> -  final BodyElement body;
按模型 body 也需要存在的，可以是getter

2021-04-26 09:53 UTC, wssgcg1213 commented on kraken/lib/src/dom/document.dart
> -  final BodyElement body;
哦直接在bridge层也可以

2021-04-26 09:53 UTC, wssgcg1213 commented on kraken/lib/src/dom/elements/script.dart
> +      // If image in tree, make sure the image-box has been layout, using addPostFrameCallback.
这里注释改一下

2021-04-26 09:53 UTC, wssgcg1213 commented on kraken/lib/src/launcher/controller.dart
> -    clearUICommand(_view.contextId);
这是啥，cc 晟怀看看有没有影响

2021-04-26 10:58 UTC, andycall requested changes

2021-04-26 10:58 UTC, andycall commented on kraken/lib/src/launcher/controller.dart
> -    clearUICommand(_view.contextId);
为啥不能删了，在一些特殊情况下，Kraken 在初始化的时候，队列里面还有上个页面遗留下来的指令没有执行，所以必须要先清空队列

2021-04-26 11:35 UTC, yuanyan commented on integration_tests/assets/hello.js
> +document.body.appendChild(document.createTextNode('Hello'));
<script  src="./hello.js" />

2021-04-26 11:37 UTC, yuanyan commented on kraken/lib/src/launcher/controller.dart
> -    clearUICommand(_view.contextId);
上个页面销毁的时候已经clear了，什么情况需要在初始化clear？

2021-04-26 12:14 UTC, yuanyan commented on bridge/polyfill/src/dom.ts
> +});
document.scripts? @temper357

2021-04-26 15:58 UTC, andycall requested changes

2021-04-26 15:58 UTC, andycall commented on bridge/bindings/jsc/DOM/element.cc
> +  NativeString args_01{};
发送指令不能放在 buildElementInstance 函数，而应当放在 ElementInstance 的构造函数内。因为还存在直接使用 new 运算符创建 Element 的情况。在那种情况下，Element::instanceConstructor 会直接被调用。

2021-04-26 16:52 UTC, andycall commented on bridge/bindings/jsc/DOM/element.cc
> +  NativeString args_01{};
同时每个扩展 Element 都有自己专属的 nativePtr 指针，直接在 buildElementInstance 里面传递 nativeElement 到 dart 会引发 BAD ACCESS 异常

2021-05-11 06:40 UTC, wssgcg1213 submitted a review, later dismissed
![image](https://user-images.githubusercontent.com/3922719/68545933-c9347b80-040c-11ea-981d-ff40cf707ffa.png)

2021-05-11 09:15 UTC, temper357 submitted a review, later dismissed

2021-05-11 11:51 UTC, andycall requested changes

2021-05-11 11:51 UTC, andycall commented on kraken/lib/src/launcher/controller.dart
> -    clearUICommand(_view.contextId);
Kraken Widget 的构造的时候，会在上个页面还没有 dispose 时进行初始化，这个时候就存在问题

2021-05-12 08:00 UTC, andycall approved these changes

2021-05-12 08:34 UTC, merged