[WIP] refactor: layout constraints
openkraken/kraken pull request #224
Opened 2021-04-26 03:03 UTC by temper357

因 Kraken 旧架构的历史原因，原架构中未合并 RenderObject， constraints 是在 tree 中 RenderObject 从上往下继承，为满足 overflow 导致 children size 大于 parent 的要求，constraints 被设置成 unconstrained，这样会导致以下两个问题：
1. Flutter 在 RenderObject layout 时会判断当前 constraints 是否与旧的 constraints 相同，如果相同且 markNeedsLayout 为 false 时会跳过 layout，此时会导致 Kraken 一些 style 变化场景 children 无法更新。（ 如百分比场景相关 issue https://github.com/openkraken/kraken/issues/183  https://github.com/openkraken/kraken/issues/160 ）
2. Flutter 在 RenderObject  layout 时如果当前节点的 constraints 为 tight 时会限制 relayoutBoundary 为当前节点，此时 markNeedsLayout 不会往上递归，这样某个节点 style 属性变更时，只会向上递归到 constraints 为 tight 的节点不会到 root，提升了 layout 性能。

鉴于以上两个原因，Kraken 重构 layout constraints 逻辑，根据 style 提前将 constraints 计算好，如果能完全推断出 size 的场景（如 width/height 固定）则设为 tight constraints，不能完全推断出 size  的场景（如设置 min-width, flex-basis 了 size 依赖于 children 的 size 的场景）则设最小 constraints。

2021-04-30 09:57 UTC, yuanyan commented on integration_tests/specs/css/css-flexbox/percentage.ts
> +              createText('暂时没有问答动态哦asdfas阿斯顿空军飞机阿克琉斯的风景阿娇的事阿克琉斯解放军卡拉斯地方～')
测试文本尽可能有统一规则，避免无意义的文字

2021-04-30 09:57 UTC, yuanyan commented on integration_tests/specs/dom/elements/img.ts
> +  xit('should work with loading=lazy', (done) => {
为什么 xit？

2021-05-06 04:31 UTC, yuanyan commented on integration_tests/specs/dom/elements/img.ts
> +  xit('should work with loading=lazy', (done) => {
看到说明了，这里可以考虑 sleep 看下

2021-05-06 11:06 UTC, wssgcg1213 commented on kraken/lib/src/rendering/box_model.dart
> +      if (height != null && height > maxHeight)  {
这行多了个空格

2021-05-06 11:08 UTC, wssgcg1213 requested changes

2021-05-06 11:08 UTC, wssgcg1213 commented on kraken/lib/src/rendering/box_model.dart
> +//    print('get constraints----------- $this $constraints');
去掉注释

2021-05-06 11:08 UTC, wssgcg1213 commented on kraken/lib/src/rendering/box_model.dart
> +      child.markOwnNeedsLayout();
这里为什么是 markOwnNeedsLayout 而不是 markNeedLayout?

2021-05-06 12:21 UTC, temper357 commented on integration_tests/specs/css/css-flexbox/percentage.ts
> +              createText('暂时没有问答动态哦asdfas阿斯顿空军飞机阿克琉斯的风景阿娇的事阿克琉斯解放军卡拉斯地方～')
已修改成描述与测试用例相关的英文

2021-05-06 12:52 UTC, temper357 commented on kraken/lib/src/rendering/box_model.dart
> +      child.markOwnNeedsLayout();
1. 由于 Flutter 并没有对外暴露 RenderObject 是否需要 layout 的变量（只有一个 debug 环境能访问的 debugNeedsLayout），因此 Kraken 在 RenderBoxModel 上定义了一个 needsLayout 变量用来映射  debugNeedsLayout 变量，needsLayout 用来在 Layout 时进行性能优化时用，markOwnNeedsLayout 正是用来设置 needsLayout 变量用的。  
2. Flutter 内部除了 markNeedsLayout 时会修改 debugNeedsLayout，还有 dropChild 与 layout 时有修改 debugNeedsLayout 的逻辑，因此 Kraken 在 RenderBoxModel 上 override 了这两个方法用来同步修改 needsLayout 变量，上面的代码正是在这两个 override 的方法处调用。

2021-05-07 03:23 UTC, wssgcg1213 commented on kraken/lib/src/rendering/box_model.dart
> +      child.markOwnNeedsLayout();
这个实现我看懂了, 我的问题是这里为什么不用 markNeedsLayout, 区别是 markOwnNeedsLayout 只是标记了自己私有的 needLayout = true, 并没有使得这个节点添加到需要被触发 layout 的节点列表里, 可以看一下 super 的逻辑, 有 
```
owner!._nodesNeedingLayout.add(this);
owner!.requestVisualUpdate();
```

2021-05-07 03:24 UTC, wssgcg1213 commented on kraken/lib/src/rendering/box_model.dart
> +      child.markOwnNeedsLayout();
所以我担心 performLayout 的触发时机并不一定是下一帧, 而是看后续其它的 markNeedsLayout 操作的后一帧

2021-05-07 08:45 UTC, temper357 commented on kraken/lib/src/rendering/box_model.dart
> +      child.markOwnNeedsLayout();
因为这个 dropChild 方法是 override RenderObject 的 dropChild 方法，在  super.dropChild 中已经调用过 markNeedsLayout()，所以不用重复设置。

2021-05-10 03:21 UTC, temper357 commented on kraken/lib/src/rendering/box_model.dart
> +      if (height != null && height > maxHeight)  {
fixed

2021-05-10 03:21 UTC, temper357 commented on kraken/lib/src/rendering/box_model.dart
> +//    print('get constraints----------- $this $constraints');
fixed

2021-05-12 03:19 UTC, temper357 commented
关于 lazyload 的图片修复了两个问题：
1. 有 repaintBoundary 时图片不展示（如设置 transform），原因是之前 RenderImage 是在 style apply 之前 append 上去，对于 lazyload 的图片会设置 intersection observer listener，此时由于 style 未设置，设置 listener 的 renderBoxModel 是还未转 repaintBoundary 的 renderBoxModel，因此 listener 永远不会触发，fix 为将 RenderImage append 逻辑移到 didAttachRenderer，等待 style 设置完毕。
2. 设置 objectFit/objectPosition 时 RenderImage 还未 append，正确是将 objectFit/objectPosition 抽离到 renderStyle，等待append RenderImage 时再设置上去。

集成测试不通过([issue](https://github.com/openkraken/kraken/issues/269))原因是只设置 width 不设置 height 时在集成测试时 intersection observer 不触发，但是正常渲染能触发，main 上也有这个问题，只是由于 FlushLayout 时多渲染了一次导致刚好能通过，intersection observer 不触发具体原因还未找到，这个 PR 可以先合掉。

2021-05-12 04:18 UTC, wssgcg1213 approved these changes
![image](https://user-images.githubusercontent.com/3922719/68545933-c9347b80-040c-11ea-981d-ff40cf707ffa.png)

2021-05-12 04:29 UTC, andycall requested changes

2021-05-12 04:29 UTC, andycall commented on integration_tests/specs/dom/elements/img.ts
> +  xit('should work with loading=lazy', (done) => {
lazy应该修好了吧，我看下面的 lazy 测试都 work 了

2021-05-12 06:13 UTC, temper357 commented on integration_tests/specs/dom/elements/img.ts
> +  xit('should work with loading=lazy', (done) => {
没有，下面的 lazy 测试是 width 和 height 都设置，xit 这个是只设置 width 不设置 height。

2021-05-13 12:04 UTC, yuanyan commented on kraken/lib/src/css/margin.dart
> +      if (renderBoxModel.parent is RenderBoxModel) {
这注释写的逻辑应该是网上递归 mark 吧，感觉这代码不太对劲

2021-05-13 12:09 UTC, yuanyan commented on kraken/lib/src/rendering/flow.dart
> +    void iterateRunMetrics(_RunMetrics runMetrics) {
避免在方法中定义方法吧，考虑移出来

2021-05-13 12:21 UTC, temper357 commented on kraken/lib/src/css/margin.dart
> +      if (renderBoxModel.parent is RenderBoxModel) {
注释想表达的意思是本来 Flutter 中 markNeedsLayout 会向上递归，但是遇到 constraints 为 tight 时，relayoutBoundary 会等于自身，这时并不会向上递归，导致需要额外 mark parent needsLayout，否则 parent 不会重新 layout。

2021-05-13 13:28 UTC, temper357 commented on kraken/lib/src/rendering/flow.dart
> +    void iterateRunMetrics(_RunMetrics runMetrics) {
fixed

2021-05-13 14:47 UTC, yuanyan approved these changes

2021-05-13 14:48 UTC, merged