Update input.dart
openkraken/kraken pull request #297
Opened 2021-05-11 03:11 UTC by qingyangmoke

修复input在添加dom树之前设置value不生效的问题

2021-05-11 03:14 UTC, answershuto commented
请增加用例

参考： http://openkraken.com/guide/contribute/test

2021-05-12 04:25 UTC, andycall commented
@qingyangmoke 还缺一张你那个测试生成的截图，可以在这里找到，然后再把它提交上了

![image](https://user-images.githubusercontent.com/4409743/117918150-186aad80-b31d-11eb-9416-158ff61ae33b.png)

2021-05-12 04:26 UTC, andycall requested changes
需要补充测试截图

2021-05-12 08:16 UTC, andycall approved these changes

2021-05-12 08:36 UTC, yuanyan approved these changes

2021-05-12 08:36 UTC, merged