[WIP]Fix/webview scroll
openkraken/kraken pull request #398
Opened 2021-06-07 12:53 UTC by answershuto

2021-06-15 03:07 UTC, wssgcg1213 commented on kraken/lib/src/dom/window.dart
> -  double scrollX() {
scrollX 是部署在 window 上的, 原来是符合标准的, 放到 document 上反而不对了 
https://developer.mozilla.org/zh-CN/docs/Web/API/window/scrollX

2021-06-15 03:08 UTC, wssgcg1213 commented on kraken/lib/src/dom/window.dart
> +    document.addEvent(eventName);
这个应该在 switch 的 default 里边吧, 否则比如现在的 scroll 时间会出现监听两次的情况

2021-06-15 03:09 UTC, wssgcg1213 commented on kraken/lib/src/gesture/gesture_manager.dart
> +    if (_hitTestList.length != 0) {
其实这里可以用 `.isNotEmpty`

2021-06-15 03:10 UTC, wssgcg1213 commented on kraken/lib/src/rendering/pointer.dart
> +typedef EventHandlers = Map<String, List<EventHandler>> Function();
GetEventHandlers

2021-06-16 12:45 UTC, yuanyan commented on kraken/lib/src/dom/window.dart
> -  double scrollX() {
是的，viewportElement 不能简单的理解为 documentElement，不是一个东西

2021-06-17 05:37 UTC, yuanyan commented on bridge/bindings/jsc/DOM/event_target.cc
> +  // init list.
首字母大写开头

2021-06-18 03:28 UTC, wssgcg1213 commented on kraken/lib/src/gesture/gesture_manager.dart
> +    _target!.onLongPress!(
1

2021-06-18 08:27 UTC, andycall requested changes

2021-06-18 08:27 UTC, andycall commented on bridge/bindings/jsc/DOM/event_target.cc
> +   if (handlers.empty()) {
这个 Patch 修好之后，这里的逻辑就有 bug 了，得还需要判断  _propertyEventHandler

https://github.com/openkraken/kraken/pull/426/files

2021-06-18 09:24 UTC, andycall approved these changes

2021-06-18 09:24 UTC, yuanyan approved these changes

2021-06-18 09:24 UTC, merged