[WIP] refactor: remove targetId and elementManager in RenderBoxModel
openkraken/kraken pull request #452
Opened 2021-06-28 03:07 UTC by temper357

Closes https://github.com/openkraken/kraken/issues/124

2021-07-01 11:23 UTC, andycall requested changes

2021-07-01 11:23 UTC, andycall commented on kraken/lib/src/dom/element.dart
> +  Function markRendererNeedsLayout;
这里应该用 typedef 写清每个函数的定义参数和返回值，而不是用一个 Function

2021-07-01 11:39 UTC, wssgcg1213 approved these changes

2021-07-01 11:40 UTC, temper357 commented on kraken/lib/src/dom/element.dart
> +  Function markRendererNeedsLayout;
fixed

2021-07-01 11:41 UTC, andycall submitted a review, later dismissed

2021-07-02 11:13 UTC, andycall approved these changes

2021-07-02 12:50 UTC, merged