[WIP]Feat/support html
openkraken/kraken pull request #469
Opened 2021-07-05 12:23 UTC by answershuto

支持 HTML 格式以支持 SSR 优化加载速度。

2021-07-08 14:23 UTC, yuanyan commented on kraken/lib/src/launcher/bundle.dart
> +    if (url.toString().contains('.html')) {
首先是通过 mimeType，然后是通过文件后缀

2021-07-08 14:56 UTC, andycall commented
把 third_party 里面的文章单独提个 PR 吧

2021-07-08 14:57 UTC, andycall requested changes

2021-07-08 14:57 UTC, andycall commented on bridge/CMakeLists.txt
> +    ${CMAKE_CURRENT_SOURCE_DIR}/third_party/gumbo-parser/src/attribute.c
添加一个新的 library target

2021-07-15 12:11 UTC, andycall requested changes

2021-07-15 12:11 UTC, andycall commented on bridge/bridge_jsc.cc
> +  #if ENABLE_PROFILE
这里缩进不太对

2021-07-15 12:12 UTC, andycall commented
少了些测试

2021-07-21 02:40 UTC, answershuto commented
> 少了些测试

测试我单独开了个 issue 增加 HTML 能力的 CI 能力，然后单独提一个 pr，这个功能在 assets/bundle.html 下的文件验证过。

2021-07-21 05:55 UTC, yuanyan commented on kraken/example/assets/bundle.html
> +
去掉头部空格

2021-07-21 05:56 UTC, yuanyan commented on kraken/example/assets/bundle.html
> +  <title> I'm a html demo</title>
title 还没有支持

2021-07-21 05:57 UTC, yuanyan commented on kraken/example/assets/bundle.html
> +  <p data-test="123" style="text-align:center;color:red">
`data-test="123" ` 可以移除，`text-align:center;color:red` -> `text-align:center; color:red`

2021-07-21 05:57 UTC, yuanyan commented on kraken/example/assets/bundle.html
> +<script src="./assets/bundle.js" ></script>
script 应该在body内

2021-07-30 07:45 UTC, answershuto commented on kraken/lib/src/dom/elements/script.dart
> +      _fetchBundle(src);
看起来是得前置判断当前 JS 上下文是否已销毁。
这个问题在 reload 的时候应该也是一样的。
我提个 issue。 https://github.com/openkraken/kraken/issues/552

2021-08-04 03:59 UTC, andycall approved these changes

2021-08-04 09:47 UTC, temper357 approved these changes

2021-08-04 10:01 UTC, merged