feat: add request queue avoid io error
openkraken/kraken pull request #543
Opened 2021-07-28 11:55 UTC by yuanyan

2021-08-04 03:38 UTC, andycall commented
```
1) XMLHttpRequest POST method success
  Message:
    Expected 0 to be 200.
  Stack:
    specs.build.js:94894:28
    dispatchEvent@[native code]
    promiseReactionJob@[native code]
  Message:
    Error: Timeout - Async function did not complete within 5000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL) in internal:// (line 6480)
  Stack:
    

2) XMLHttpRequest POST method fail
  Message:
    Expected 0 to be 405.
  Stack:
    specs.build.js:94916:28
    dispatchEvent@[native code]
    promiseReactionJob@[native code]
  Message:
    Error: Timeout - Async function did not complete within 5000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL) in internal:// (line 6480)
  Stack:
```

@yuanyan

2021-08-09 03:27 UTC, answershuto commented on kraken/lib/src/foundation/http_client_request.dart
> +final _requestQueue = Queue(parallel: 10);
这个 10 是跟浏览器一致的吗？

2021-08-09 07:09 UTC, andycall commented
有冲突

2021-08-10 14:51 UTC, yuanyan commented on kraken/lib/src/foundation/http_client_request.dart
> +final _requestQueue = Queue(parallel: 10);
不同浏览器并不一样的

2021-08-11 02:05 UTC, wssgcg1213 commented on kraken/lib/src/foundation/http_overrides.dart
> +  // FIXME: will override existed
这里已经处理过 override 了

See 
1. KrakenHttpOverrides@parentHttpOverrides, 这个 member 在实例化  KrakenHttpOverrides 的时候保存了 HttpOverrides.current 的引用  
2. override 方法 HttpClient createHttpClient() 会优先判断 parentHttpOverrides.createHttpClient 存在否导出 nativeHttpClient

2021-08-11 02:06 UTC, wssgcg1213 commented on kraken/lib/src/foundation/http_overrides.dart
> +  // FIXME: will override existed
另外因为 KrakenHttpOverrides 是 singleton, 所以不需要考虑多级 override, HttpOverrides.current 也是单个, 所以只考虑一层即可

2021-08-11 02:08 UTC, wssgcg1213 commented on kraken/lib/src/launcher/controller.dart
> +    assert(!_view._disposed, 'Kraken have already disposed');
have `been` disposed, since dispose is a force verb; or using `released`.

2021-08-11 02:11 UTC, wssgcg1213 commented on kraken/lib/src/launcher/controller.dart
> +    assert(!_view._disposed, 'Kraken have already disposed');
同样的 check 可以精简为一个方法, 就像 sky_engine 里面的类似逻辑
![image](https://user-images.githubusercontent.com/3922719/128959033-5f8e65b5-4c2a-4774-8815-69fe78eaaf69.png)

2021-08-11 02:13 UTC, wssgcg1213 commented on kraken/lib/src/module/fetch.dart
> +      return http.post(uri, headers: headers, body: options['body']);
这里应该有 http.open(method: method) 这样的方法吧, 因为最终 method 只是 HTTP Request Header 中的一个字段, 这样的 switch-case 看起来无法枚举完整, 比如 "OPTION" 就不在里边

2021-08-11 04:28 UTC, wssgcg1213 requested changes

2021-08-11 04:28 UTC, wssgcg1213 commented on kraken/lib/src/module/fetch.dart
> +Future<http.Response> _fetch(String url, Map<String, dynamic> options, { required int contextId }) async {
参数直接传 uri 会好一点吧

2021-08-11 13:31 UTC, closed without merging