[WIP]Feat/support HMR
openkraken/kraken pull request #545
Opened 2021-07-29 03:43 UTC by answershuto

支持 HMR 能力方便开发者调试。

2021-08-02 03:50 UTC, answershuto commented
https://user-images.githubusercontent.com/17812136/127801983-369a45f7-3358-4b0b-8b51-fe0f89ed399c.mov

2021-08-03 10:07 UTC, answershuto commented
https://user-images.githubusercontent.com/17812136/127997960-1577dce7-50cf-4ec8-8a51-435133b846e3.mov

2021-08-03 11:04 UTC, answershuto commented
https://user-images.githubusercontent.com/17812136/128005108-4e44de05-848b-4708-82ac-5c5243b8dbf0.mov

2021-08-03 11:54 UTC, yuanyan commented on bridge/polyfill/src/dom.ts
> +window.ShadowRoot = () => {};
这个空实现有风险，会导致特征判断有问题

2021-08-03 11:56 UTC, yuanyan commented on integration_tests/specs/dom/elements/script.ts
> +    x.src = 'file://assets/hello.js';
file是基于文件系统的， 这个改动是有问题的

2021-08-03 12:00 UTC, yuanyan commented on bridge/polyfill/src/xhr.ts
> +    if (!/^([a-z][a-z\d\+\-\.]*:)?\/\//.test(url)) {
这个相对路径的判断，在img、fetch下也都是需要的，可以考虑在dart层统一实现

2021-08-03 12:07 UTC, answershuto commented on bridge/polyfill/src/dom.ts
> +window.ShadowRoot = () => {};
Vue 有一个版本没有加特征判断，直接 instanceOf，导致我们这 JS 直接报右值不对，error 了阻塞主流程了。
最新版本是加了特征判断，但是如果不这样实现，老版本直接白屏了。

2021-08-03 12:15 UTC, answershuto commented on bridge/polyfill/src/xhr.ts
> +    if (!/^([a-z][a-z\d\+\-\.]*:)?\/\//.test(url)) {
img、fetch 我疏漏了，我补充一下做一层抽象。

2021-08-03 12:20 UTC, answershuto commented on bridge/polyfill/src/dom.ts
> +window.ShadowRoot = () => {};
然后，这里的空实现的目的是为了支持 instanceOf 的判断的，Kraken 短期看不会支持 shadow DOM，所以提供这个空实现，让需要判断 instanceOf ShadowRoot 的工具可以正常  work，空实现是为了 instanceOf 返回一定是 false，这个逻辑在 Kraken 内是正确的。

2021-08-10 07:23 UTC, andycall requested changes

2021-08-10 07:23 UTC, andycall commented on kraken/lib/src/foundation/url.dart
> +abstract class URLClient {
URLClient 这个命名不太合适，看上去应该功能很多，结果只有一个 parse

2021-08-11 02:30 UTC, wssgcg1213 commented on kraken/lib/src/foundation/url.dart
> +        path = httpClientInterceptor.customURLParser(path, url);
Negative

2021-08-11 02:49 UTC, wssgcg1213 requested changes

2021-08-11 02:49 UTC, wssgcg1213 commented on kraken/lib/src/foundation/url.dart
> +    if(contextId != null) {
space

2021-08-11 02:49 UTC, wssgcg1213 commented on kraken/lib/src/foundation/url.dart
> +      HttpClientInterceptor? httpClientInterceptor = controller.httpClientInterceptor;
这个跟 Http 没有关系

2021-08-11 02:49 UTC, wssgcg1213 commented on kraken/lib/src/foundation/url.dart
> +      String href = controller.href;
换一个顺序

2021-08-11 02:49 UTC, wssgcg1213 commented on kraken/lib/src/foundation/url.dart
> +      RegExp exp = RegExp("^([a-z][a-z\d\+\-\.]*:)?\/\/");
正则可以 const static

2021-08-11 02:49 UTC, wssgcg1213 commented on kraken/lib/src/launcher/controller.dart
> +  void updateHref(String url) {
set href(String value) {}

2021-08-11 02:49 UTC, wssgcg1213 commented on kraken/lib/src/launcher/bundle.dart
> +    if (needUpdateUrl == true) {
去掉 == true

2021-08-11 02:49 UTC, wssgcg1213 commented on kraken/lib/src/launcher/bundle.dart
> +  static Future<KrakenBundle> getBundle(String path, { String? contentOverride, required int contextId, bool? needUpdateUrl }) async {
1. 不要用 nullable, bool 可以默认 false
2. 命名上需要再想一下, 抽象

2021-08-11 02:49 UTC, wssgcg1213 commented on kraken/lib/src/foundation/http_client_interceptor.dart
> +  String customURLParser(String url, String originURL);
这个地方不对

2021-08-11 02:49 UTC, wssgcg1213 commented on kraken/lib/src/launcher/bundle.dart
> +  final String url;
这里原来的 Uri 对象更好一点

2021-08-11 02:49 UTC, wssgcg1213 commented on kraken/lib/src/launcher/bundle.dart
> +    NetworkAssetBundle bundle = NetworkAssetBundle(URLParser(url, contextId: contextId).url, contextId: contextId);
class UriParser
`Uri parser.parse(String)`

2021-08-11 02:49 UTC, wssgcg1213 commented on kraken/lib/src/module/fetch.dart
> +Future<Response> _fetch(String path, Map<String, dynamic> map, { required int contextId }) async {
fetch 的第一个参数就是 Url

path 也是合法的 url

2021-08-11 03:05 UTC, wssgcg1213 commented
class UriParser {
  final int contextId;
  UriParser(this.contextId);

  Uri parse(String input) {
    // .....

  }

  UriInterceptor _interceptor;
  set interceptor(UriInterceptor value) {
    
  }

  void dispose() {}
}

KrakenController.init = () {
  this.uriParser = UriParser(contextId);
}

KrakenController.dispose = () => {
uriParser.dispose
}

abstract class UriInterceptor {
  Uri interceptUri(Uri uri);
}

// ... User

class MyUriInterceptor implements UriInterceptor {
  @override
  Uri interceptUri(Uri uri) {

    return ...;
  }
}

Kraken(
  uriInterceptor: MyUriInterceptor(),
)

2021-08-11 08:39 UTC, wssgcg1213 commented on integration_tests/lib/main.dart
> +  Uri parse(Uri uri, Uri originUri) {
为啥有两个参数呀

2021-08-11 08:39 UTC, wssgcg1213 commented on kraken/lib/src/css/background.dart
> +import 'package:kraken/kraken.dart';
应该是引入 kraken/foundation.dart 吧

2021-08-11 08:41 UTC, wssgcg1213 commented on kraken/lib/src/css/background.dart
> +      url = controller.uriParser!.parse(Uri.parse(url)).toString();
这个 url 就应该是 Uri 类型

2021-08-11 08:43 UTC, wssgcg1213 commented on kraken/lib/src/launcher/controller.dart
> +      _bundle = await KrakenBundle.getBundle(url ?? '', contentOverride: _bundleContent, contextId: view.contextId, isLoadPage: true);
这个地方还是很奇怪, getBundle 的时候为啥还有一个 isLoadPage

2021-08-11 08:44 UTC, wssgcg1213 commented on kraken/lib/src/foundation/url.dart
> +  void registerInterceptor(UriInterceptor? uriInterceptor) {
唯一值的话用 setter 比较好

2021-08-11 08:44 UTC, wssgcg1213 commented on kraken/lib/src/foundation/url.dart
> +  void registerInterceptor(UriInterceptor? uriInterceptor) {
参数不要允许 nullable

2021-08-11 08:46 UTC, wssgcg1213 commented on kraken/lib/src/foundation/url.dart
> +      return _uriInterceptor!.parse(Uri.parse(path), uri);
应该只传一个值, 你的上面的默认逻辑其实可以抽象为 defaultUriInterceptor, 跟用户自定义的可以级联

2021-08-11 08:49 UTC, answershuto commented on integration_tests/lib/main.dart
> +  Uri parse(Uri uri, Uri originUri) {
这里的设计是， uri 是 default intercepter 处理以后的值， originUri 是处理之前的，把处理权交给用户，用户可能是希望在 default 的基础上做一些定制化判断，而不是整个逻辑都重写。

2021-08-11 08:49 UTC, answershuto commented on kraken/lib/src/foundation/url.dart
> +      return _uriInterceptor!.parse(Uri.parse(path), uri);
default 同上

2021-08-11 08:50 UTC, answershuto commented on kraken/lib/src/css/background.dart
> +import 'package:kraken/kraken.dart';
KrakenController

2021-08-11 08:51 UTC, answershuto commented on kraken/lib/src/css/background.dart
> +      url = controller.uriParser!.parse(Uri.parse(url)).toString();
CSSUrl.parseUrl 是个  String 类型

2021-08-11 11:18 UTC, answershuto commented
讨论结论： 以继承 UriParser 的方式来实现用户自定义 URi 解析。

```dart
class CustomUriParser extends UriParser {
  @override
  Uri parse(int contextId, Uri originUri) {
    Uri uri = super.parse(contextId, originUri);

    if (uri.toString().contains('assets')) {
      return originUri;
    }
    return uri;
  }
}
```

2021-08-11 12:46 UTC, yuanyan commented on bridge/polyfill/src/dom.ts
> +window.ShadowRoot = () => {};
需要从合理性角度看，不是从解决Vue问题的角度

2021-08-11 12:48 UTC, yuanyan commented on kraken/lib/src/css/background.dart
> +import 'package:kraken/kraken.dart';
+1，需要在kraken内部避免引入 kraken/kraken.dart

2021-08-11 12:48 UTC, yuanyan commented on kraken/lib/src/foundation/url.dart
> +class UriParser {
文件名是 url，为什么类是 uri

2021-08-11 12:50 UTC, yuanyan commented on kraken/lib/src/foundation/url.dart
> +class UriParser {
类的命名需要避免冗余，考虑 class uri { parse () }  或一个函数，不是 class uriparser { parse }

2021-08-11 12:54 UTC, yuanyan requested changes
一些细节需要优化下

2021-08-12 07:25 UTC, andycall commented on bridge/polyfill/src/dom.ts
> +window.ShadowRoot = () => {};
删了好了

2021-08-12 07:29 UTC, andycall requested changes

2021-08-12 07:29 UTC, andycall commented on kraken/lib/src/module/fetch.dart
> +    String url = (moduleManager!.controller.uriInterceptor.parse(moduleManager!.contextId, Uri.parse(method))).toString();
这里不判空吗？

2021-08-12 07:29 UTC, andycall commented on kraken/lib/src/launcher/controller.dart
> +    UriInterceptor? uriInterceptor,
直接挂 this 上不可以吗？

2021-08-12 07:47 UTC, answershuto commented on bridge/polyfill/src/dom.ts
> +window.ShadowRoot = () => {};
我放到 vue demo 的polyfill 里面

2021-08-12 08:22 UTC, andycall submitted a review, later dismissed

2021-08-12 11:14 UTC, wssgcg1213 approved these changes

2021-08-12 11:22 UTC, andycall approved these changes

2021-08-12 12:33 UTC, merged