[WIP] fix: transition execution timing
openkraken/kraken pull request #559
Opened 2021-08-03 12:43 UTC by temper357

Closes https://github.com/openkraken/kraken/issues/523
Closes https://github.com/openkraken/kraken/issues/515

修复 transition 动画的执行时机，参考 webkit animation 需要在 style 全部设置完成后才执行，而 Kraken 动画是在 style 设置过程中通过设置延时将 transition 延迟到下一帧执行，这带来几个问题：
1. transition 的执行强依赖 style 的顺序，当 transition 指定的 property 在 transition 之前定义时将不生效，如 `transform: tranlate(100px, 0); transition: all 1s ease;`。 
2. transition 的执行时机不对，transition 必须要 node layout 完成后的下一帧才生效，因此必须在 requestFrameAnimation 或者 setTimeout 后才会生效，目前 Kraken 只判断了初始值是否为 null 或者 length 是否为 auto 是不够的。

2021-08-09 07:11 UTC, andycall commented on kraken/lib/src/bridge/to_native.dart
> +          case UICommandType.setStyle:
这里已经有了 setStyle，上面的 setStyle 是不是就不需要了

2021-08-09 07:13 UTC, andycall commented on kraken/lib/src/rendering/box_model.dart
> +  bool get firstLayouted => _firstLayouted;
firstLayouted 这个 API 有点奇怪，感觉是 hack 设计。

2021-08-09 07:16 UTC, andycall requested changes

2021-08-09 07:16 UTC, andycall commented on kraken/lib/src/bridge/to_native.dart
> +          case UICommandType.setStyle:
为啥是 setStyle 的 command 触发 setRenderStyle。 这个流程设计不太好

2021-08-09 07:16 UTC, andycall commented on kraken/lib/src/bridge/to_native.dart
> +          case UICommandType.setStyle:
把 stylelistener 的触发逻辑放在这里，而不是由 setStyle 触发。

在这里只需要调用一个函数触发 styleListener 就可以了。或许应该叫 flushStyleListener ?

2021-08-09 07:31 UTC, temper357 commented on kraken/lib/src/rendering/box_model.dart
> +  bool get firstLayouted => _firstLayouted;
是有点 hack，原因是浏览器中 transition 生效的条件是需要 transition-property 对应的属性在上一帧已经被初始化过，也就是 getComputedStyle 能拿到这个属性的值，对应 Kraken 来说也就是需要保证设置 transition 属性时 renderBoxModel 已经渲染过第一帧，如果有其他方式能拿到这个状态替代此 hack 更好。

2021-08-10 07:24 UTC, andycall approved these changes

2021-08-10 07:33 UTC, answershuto approved these changes

2021-08-10 07:33 UTC, merged