[WIP] :sparkles: feat: introduce http cache
openkraken/kraken pull request #580
Opened 2021-08-10 10:41 UTC by wssgcg1213

Close #373

2021-08-11 09:04 UTC, answershuto requested changes

2021-08-11 09:50 UTC, wssgcg1213 commented on kraken/lib/src/foundation/http_cache.dart
> +      contextUri = Uri(scheme: 'https', host: contextUri.host, port: contextUri.port);
得等 #545  先合进去

2021-08-11 13:07 UTC, yuanyan commented on kraken/lib/src/foundation/http_cache.dart
> +  static final String _cachePath = "Kraken/HttpCaches";
“ =》'

2021-08-11 13:08 UTC, yuanyan commented on kraken/lib/src/foundation/http_cache.dart
> +  static String _getOrigin(Uri contextUri) {
contextUri 概念需要优化下

2021-08-11 13:17 UTC, yuanyan commented on kraken/lib/src/foundation/http_cache.dart
> +    String? contextUrl;
contextUrl 的概念需要优化

2021-08-11 13:18 UTC, yuanyan commented on kraken/lib/src/foundation/http_cache.dart
> +    String origin = _getOrigin(Uri.parse(contextUrl ?? 'anonymous://'));
协议头应该要标准化的内容

2021-08-11 13:20 UTC, yuanyan commented on kraken/lib/src/foundation/http_cache.dart
> +  static Future<HttpClientResponse> cacheHttpResource(
cache 是不有更适合的动词太替代

2021-08-11 13:21 UTC, yuanyan commented on kraken/lib/src/foundation/http_cache.dart
> +  static final String _cachePath = "Kraken/HttpCaches";
cache 目录统一管理https://github.com/openkraken/kraken/blob/feat/cache/kraken/lib/src/painting/cached_network_image.dart#L43

2021-08-12 11:45 UTC, andycall commented
需要一些测试，可以用 dart 写一些单元测试

2021-08-13 06:01 UTC, answershuto commented on kraken/lib/src/foundation/environment.dart
>  const bool PRODUCTION = bool.fromEnvironment('dart.vm.product');
这个 PRODUCTION 还有地方用到嘛？

2021-08-13 06:17 UTC, wssgcg1213 commented on kraken/lib/src/foundation/environment.dart
>  const bool PRODUCTION = bool.fromEnvironment('dart.vm.product');
不太清楚, 未改动此处

2021-08-13 07:16 UTC, answershuto commented on kraken/lib/src/foundation/environment.dart
>  const bool PRODUCTION = bool.fromEnvironment('dart.vm.product');
全局搜了一下似乎没有用到？

2021-08-14 05:12 UTC, yuanyan commented on kraken/lib/src/painting/image_provider_factory.dart
> +  int? contextId;
与 defaultNetworkProviderFactory 里一致，可以抽成私有的公共方法？

2021-08-16 08:33 UTC, wssgcg1213 commented on kraken/lib/src/foundation/environment.dart
>  const bool PRODUCTION = bool.fromEnvironment('dart.vm.product');
So, 可以删除?

2021-08-16 08:34 UTC, wssgcg1213 commented on kraken/lib/src/painting/image_provider_factory.dart
> +  int? contextId;
是的, 参考了; 我抽一个方法吧

2021-08-17 02:50 UTC, wssgcg1213 commented on kraken/lib/src/foundation/environment.dart
>  const bool PRODUCTION = bool.fromEnvironment('dart.vm.product');
已经删除, 可以使用 kDebugMode 常量代替

2021-08-17 02:50 UTC, wssgcg1213 commented on kraken/lib/src/painting/image_provider_factory.dart
> +  int? contextId;
DONE

2021-08-17 02:51 UTC, wssgcg1213 commented on kraken/lib/src/foundation/environment.dart
> -const bool PRODUCTION = bool.fromEnvironment('dart.vm.product');
确认无使用, 删除

2021-08-18 06:58 UTC, andycall commented on kraken/lib/src/foundation/http_cache_object.dart
> +        } else if (cacheControl.startsWith('max-age=')) {
还存在这种情况，使用 startsWith 是不是不太妥

```
Cache-Control: public, max-age=200
```

2021-08-19 02:09 UTC, wssgcg1213 commented on kraken/lib/src/foundation/http_cache_object.dart
> +        } else if (cacheControl.startsWith('max-age=')) {
See L88, `cacheControls` 是一个 `List<String>`, 你的这种 case 已经被解析为 ["public", "max-age=200"], 整个逻辑已经处理了这种情况; public 和 private 的处理比较复杂, 所以没有实现(可以看一下标准, 主要是用于缓存是否区分域隔离, 问题不大), 其它关键词实现了 no-store/no-cache/max-age

2021-08-19 02:47 UTC, answershuto commented on integration_tests/specs/css/css-display/containing-block.ts
> -    BODY.appendChild(div1);
这个 BODY 为啥要改了？测试环境会全局注入的吧？ BODY = document.body;

2021-08-19 02:47 UTC, answershuto commented on kraken/lib/src/foundation/environment.dart
> +    _krakenTemporaryPath = temporaryDirectory.path + '/Kraken';
'/Kraken' 拿出来 const String  吧。

2021-08-19 02:49 UTC, temper357 commented on integration_tests/lib/main.dart
> +import 'package:kraken/css.dart';
这个依赖是不是多余的，看改动处没有用到 css

2021-08-19 02:56 UTC, temper357 commented on kraken/lib/src/css/values/url.dart
> +        imageProvider = getImageProviderFactory(ImageType.cached)(url, [contextId]);
两个分支的参数改成一样的话，可以不用 if 分支，合并成一个语句判断 ImageType 类型就好

2021-08-19 02:59 UTC, temper357 commented on kraken/lib/src/dom/elements/img.dart
> +        Uri baseUrl = Uri.parse(elementManager.controller.href);
baseUrl -> baseUri ?

2021-08-19 03:00 UTC, wssgcg1213 commented on integration_tests/specs/css/css-display/containing-block.ts
> -    BODY.appendChild(div1);
IDE 提示 Error 了, 主要是复制到 Kraken 里跑找不到变量, 这样直接一点

2021-08-19 07:36 UTC, wssgcg1213 commented on kraken/lib/src/foundation/environment.dart
> +    _krakenTemporaryPath = temporaryDirectory.path + '/Kraken';
![image](https://user-images.githubusercontent.com/3922719/130027461-b902ec94-5469-4532-8029-1e325d649de0.png)
https://dart.dev/guides/language/language-tour

字符串字面量就是一种编译时常量

2021-08-19 07:40 UTC, wssgcg1213 commented on integration_tests/lib/main.dart
> +import 'package:kraken/css.dart';
![image](https://user-images.githubusercontent.com/3922719/130028097-4c6920ec-5c9c-4399-a06e-e085f5a14176.png)
删除的话这里会报红

2021-08-19 07:41 UTC, wssgcg1213 commented on integration_tests/lib/main.dart
> +import 'package:kraken/css.dart';
只是移动了位置, 因为 c 的字母序在 d 前面, 故移动到此

2021-08-19 07:43 UTC, wssgcg1213 commented on kraken/lib/src/css/values/url.dart
> +        imageProvider = getImageProviderFactory(ImageType.cached)(url, [contextId]);
也可, 我改成了这样, 
![image](https://user-images.githubusercontent.com/3922719/130028485-96680647-acdc-457e-bbfc-19809d8d7de6.png)
再看看是否没有原来清晰了?

2021-08-19 07:47 UTC, temper357 commented on kraken/lib/src/css/values/url.dart
> +        imageProvider = getImageProviderFactory(ImageType.cached)(url, [contextId]);
将三元表达式定义成变量会好一点

2021-08-19 11:37 UTC, yuanyan commented on integration_tests/specs/xhr/xhr.ts
> +    xhr.open('GET', `${MOCKED_HTTP_SERVER}/json_with_content_length_expires_etag_and_last_modified`, true);
MOCKED_HTTP_SERVER -> LOCAL_HTTP_SERVER

2021-08-19 11:41 UTC, wssgcg1213 commented on integration_tests/specs/xhr/xhr.ts
> +    xhr.open('GET', `${MOCKED_HTTP_SERVER}/json_with_content_length_expires_etag_and_last_modified`, true);
DONE

2021-08-19 11:55 UTC, yuanyan approved these changes

2021-08-19 13:34 UTC, andycall approved these changes

2021-08-19 13:34 UTC, merged