Feat/document fragment
openkraken/kraken pull request #641
Opened 2021-08-30 07:49 UTC by answershuto

2021-08-31 08:18 UTC, yuanyan commented on kraken/lib/src/dom/elements/document_fragment.dart
> +class DocumentFragmentElement extends Element {
fragment 不是 element

2021-08-31 12:01 UTC, wssgcg1213 requested changes

2021-08-31 12:01 UTC, wssgcg1213 commented on kraken/lib/src/dom/elements/document_fragment.dart
> +class DocumentFragment extends Node {
这个文件放在 dom 目录下就可以了, 它不属于 `element`

2021-09-06 11:04 UTC, answershuto commented
CI 挂掉是因为改动了 Node 在 C++ 侧的实现，插件中 C++ 扩展涉及到了 Node 的都需要重新编译。
考虑到近期插件会重新发版成 quick 版本，重新搞一遍意义不大，等 quick 版本合入后再改造该分支合入。

2021-09-24 07:17 UTC, wssgcg1213 approved these changes

2021-09-24 08:15 UTC, andycall approved these changes

2021-09-24 08:43 UTC, wssgcg1213 approved these changes

2021-09-24 08:43 UTC, merged