:recycle: refactor: rename set to add
openkraken/kraken pull request #658
Opened 2021-09-06 03:37 UTC by wssgcg1213

- Rename `setMethodCallHandler` to `addMethodCallHandler`, as which behavior is exactly `ADD`

2021-09-06 09:49 UTC, andycall approved these changes

2021-09-06 09:49 UTC, andycall commented on bridge/polyfill/src/method-channel.ts
> +  addMethodCallHandler(handler: MethodCallHandler) {
直接这么搞会 break，应该有个 deprecated warning，然后下个版本再删掉

2021-09-06 09:49 UTC, andycall requested changes
直接这么搞会 break，应该有个 deprecated warning，然后下个版本再删掉

2021-09-10 13:31 UTC, yuanyan approved these changes

2021-09-13 12:57 UTC, merged