Feat/support querySelector and querySelectorAll
openkraken/kraken pull request #672
Opened 2021-09-10 07:49 UTC by answershuto

close #41

2021-09-10 12:30 UTC, yuanyan commented on bridge/polyfill/src/dom.ts
> +// Some utility methods.
可以独立一个文件

2021-09-10 12:31 UTC, yuanyan commented on bridge/polyfill/src/dom.ts
> +let slice = function slice(arr: HTMLCollectionOf<Element>): Array<Element> {
这些工具方法在kraken下并不需要

2021-09-10 12:33 UTC, yuanyan commented on bridge/polyfill/src/dom.ts
> +  // Get By ID
By -> by, 所有注释都不太规范

2021-09-10 12:33 UTC, yuanyan commented on bridge/polyfill/src/dom.ts
> +  if (attributes.length !== 0) {
没有对应的 testcase

2021-09-17 05:57 UTC, yuanyan commented on bridge/polyfill/src/querySelector.ts
> +function fetchSelector(str: string, regex: RegExp) {
querySelector.ts  文件名风格需要统一

2021-09-22 09:33 UTC, answershuto commented on bridge/polyfill/src/querySelector.ts
> +function fetchSelector(str: string, regex: RegExp) {
已修改

2021-09-22 11:10 UTC, wssgcg1213 commented on bridge/polyfill/src/query-selector.ts
> +};
FunctionDeclaration 不需要分号结束

2021-09-22 11:27 UTC, wssgcg1213 requested changes

2021-09-22 11:27 UTC, wssgcg1213 commented on bridge/polyfill/src/query-selector.ts
> +};
同上

2021-09-22 11:27 UTC, wssgcg1213 commented on bridge/polyfill/src/query-selector.ts
> +};
1

2021-09-22 11:27 UTC, wssgcg1213 commented on integration_tests/specs/dom/nodes/document.ts
> +    })
分号

2021-09-22 11:27 UTC, wssgcg1213 commented on integration_tests/specs/dom/nodes/document.ts
> +    })
分号

2021-09-22 11:27 UTC, wssgcg1213 commented on integration_tests/specs/dom/nodes/document.ts
> +    })
1

2021-09-22 11:27 UTC, wssgcg1213 commented on integration_tests/specs/dom/nodes/document.ts
> +    })
1

2021-09-22 11:27 UTC, wssgcg1213 commented on integration_tests/specs/dom/nodes/document.ts
> +    })
1

2021-09-22 11:27 UTC, wssgcg1213 commented on integration_tests/specs/dom/nodes/document.ts
> +    })
直接找个格式化工具吧

2021-09-23 06:59 UTC, wssgcg1213 submitted a review, later dismissed

2021-09-23 08:47 UTC, temper357 commented on bridge/polyfill/src/query-selector.ts
> +  temp = fetchSelector(selector, /\[.+?\]/g);
只支持 equal，正则是不是限定下 /\[\w=\w\]/g

2021-09-23 08:48 UTC, temper357 commented on bridge/polyfill/src/query-selector.ts
> +  temp = fetchSelector(selector, /\w+/g);
element 只有一个 word 正则应该 /\w/g  就行

2021-09-23 08:52 UTC, temper357 commented on integration_tests/specs/dom/nodes/document.ts
> +  it('document querySelector cant find element', () => {
querySelector 和 querySelectorAll 的测试用例建议像 getElementByClassName 一样独立成文件，不用全部放在 document 中

2021-09-23 09:13 UTC, answershuto commented on bridge/polyfill/src/query-selector.ts
> +  temp = fetchSelector(selector, /\[.+?\]/g);
讨论了下这个正则没问题，去掉TODO。

2021-09-23 09:13 UTC, answershuto commented on bridge/polyfill/src/query-selector.ts
> +  temp = fetchSelector(selector, /\w+/g);
讨论了下这个正则没问题。

2021-09-23 09:32 UTC, wssgcg1213 approved these changes

2021-09-23 09:33 UTC, temper357 approved these changes

2021-09-23 09:33 UTC, merged