[WIP] fix: offset of lazyload positioned image
openkraken/kraken pull request #699
Opened 2021-09-22 12:43 UTC by temper357

Closes https://github.com/openkraken/kraken/issues/692

修复 lazyload 且有定位(absolute/fixed)无 left, right 的图片定位错误问题。

2021-09-22 12:47 UTC, wssgcg1213 requested changes

2021-09-22 12:47 UTC, wssgcg1213 commented on kraken/lib/src/dom/elements/img.dart
> +      parent.markNeedsLayout();
markParentNeedsLayout 我记得有这个方法

2021-09-22 12:47 UTC, wssgcg1213 commented on kraken/lib/src/rendering/intrinsic.dart
> +  bool isInLazyLoading = false;
这个概念直接暴露在 RenderIntrinsic 里面吗?

2021-09-22 12:47 UTC, wssgcg1213 commented on kraken/lib/src/dom/elements/img.dart
> +    bool _isInLazyLoading = (renderBoxModel as RenderIntrinsic).isInLazyLoading;
我觉得这种 as 的方式不是很优雅, 看起来只是一个标记而已

2021-09-23 02:58 UTC, temper357 commented on kraken/lib/src/rendering/intrinsic.dart
> +  bool isInLazyLoading = false;
RenderIntrinsic 对应的是 replaced element 的 RenderObject，replaced element 如 image, video 都可以利用懒加载技术提升首屏加载性能。

2021-09-23 03:25 UTC, temper357 commented on kraken/lib/src/dom/elements/img.dart
> +      parent.markNeedsLayout();
markParentNeedsLayout 的使用有限制，见注释

>  /// This function should only be called from [markNeedsLayout] or
>  /// [markNeedsLayoutForSizedByParentChange] implementations of subclasses that
>  /// introduce more reasons for deferring the handling of dirty layout to the
>  /// parent. See [markNeedsLayout] for details.

2021-09-24 15:55 UTC, yuanyan commented on kraken/lib/src/rendering/intrinsic.dart
> +  bool isInLazyLoading = false;
对 rendering/intrinsic.dart 来说，不应该是loading的概念了，isLazyRendering

2022-01-06 08:38 UTC, temper357 commented
对于 position 为 absolute 无 top,left 的其他 element 都会有这个定位问题，需要将这个解决方案拓展一下，这个 PR 先 close 掉另起一个。

2022-01-06 08:38 UTC, closed without merging