Canvas Path2D
openkraken/kraken pull request #71
Opened 2021-03-19 09:19 UTC by yuanyan

2021-03-19 09:23 UTC, wssgcg1213 commented on kraken/lib/src/painting/canvas_path_2d.dart
> +  // }
注释代码去掉吧

2021-03-19 09:25 UTC, wssgcg1213 commented on kraken/lib/src/painting/canvas_path_2d.dart
> +}
最底下可以留一行空行

2021-03-19 09:26 UTC, wssgcg1213 commented on kraken/lib/src/painting/canvas_path_2d.dart
> +    if (!_hasCurrentPoint())
if 的风格需要有 `{` `}`

2021-04-14 02:44 UTC, wssgcg1213 approved these changes

2021-04-15 06:21 UTC, andycall requested changes

2021-04-15 06:21 UTC, andycall commented on kraken/lib/src/dom/elements/canvas/canvas_painter.dart
> +    print('-----');
去掉日志

2021-04-15 13:17 UTC, andycall commented
测试的 API 需要调整

2021-04-19 04:49 UTC, yuanyan commented
> 测试的 API 需要调整

Updated

2021-04-19 09:26 UTC, temper357 approved these changes

2021-04-19 10:46 UTC, wssgcg1213 approved these changes

2021-04-19 10:46 UTC, andycall approved these changes

2021-04-19 10:47 UTC, merged