fix: fix ios app store
openkraken/kraken pull request #847
Opened 2021-11-04 13:43 UTC by andycall

Fixed #846

2021-11-04 13:51 UTC, wssgcg1213 requested changes

2021-11-04 13:51 UTC, wssgcg1213 commented on bridge/CMakeLists.txt
> +    OUTPUT_NAME kraken-bridge
hyphen is not allowed

2021-11-04 13:53 UTC, wssgcg1213 approved these changes

2021-11-04 13:53 UTC, wssgcg1213 commented on kraken/lib/src/bridge/platform.dart
> +    : Platform.isIOS ? 'kraken-bridge.framework/kraken_bridge' : Platform.isWindows ? '$libName.dll' : '$libName.so';
这里路径不用改吗

2021-11-04 13:54 UTC, wssgcg1213 commented on scripts/tasks.js
> +  // Generate builds scripts for ARMv7, ARMv7, ARM64
注释写多了这里

2021-11-05 01:25 UTC, cnryb commented
`kraken/ios/prepare.sh` 和 `scripts/tasks.js` 也有出现 kraken_bridge.xcframework

2021-11-05 03:47 UTC, wssgcg1213 commented
MinimumOSVersion 字段还是缺失的

2021-11-05 03:47 UTC, wssgcg1213 requested changes
MinimumOSVersion required

2021-11-05 08:25 UTC, wssgcg1213 commented on scripts/tasks.js
> +    patchiOSFrameworkPList(x64DynamicSDKPath);
simulator 的没关系, 这个不会提交到 AppStore 的

2021-11-05 08:26 UTC, andycall commented on scripts/tasks.js
> +    patchiOSFrameworkPList(x64DynamicSDKPath);
都加上吧

2021-11-08 08:02 UTC, wssgcg1213 approved these changes

2021-11-08 08:03 UTC, answershuto approved these changes

2021-11-08 08:03 UTC, merged