[WIP]Fix/window open
openkraken/kraken pull request #866
Opened 2021-11-10 12:32 UTC by answershuto

* 处理 window.open 等跳转问题
* 重构 load 传参接口设计以及逻辑，保证有 url（或 path），保证 parseURL 等处理没问题。
* history 与 bundleURL 重复设计问题是，所有历史页面（url 以及 bundleContent 等）都放到 history 中统一管理。

2021-11-23 06:09 UTC, wssgcg1213 commented
fromURL 会比 fromHref 好一点

2021-11-23 06:11 UTC, wssgcg1213 commented
href 是 Hypertext Reference 的简写

2021-11-23 06:22 UTC, answershuto commented
> 

assets 跟 url 放一起了，未来还会有 file（如果有） 等，统一当作 href 处理，内部根据协议再去判断，而不是传入的时候区分好，因为比如 src="xxxxxxx" 的情况是直接new bundle 的。

2021-11-25 03:22 UTC, wssgcg1213 requested changes
fromHref 我这边还是无法 Approve, 建议使用 fromURL

2021-11-25 03:53 UTC, wssgcg1213 commented
```
  loadUrl(String url, { Map<String, String>? additionalHttpHeaders }) {}
  loadDataWithUrl(List<int> data, String baseUrl, { String? mimeType }) {}
```

2021-11-30 06:01 UTC, yuanyan commented on kraken/lib/src/launcher/bundle.dart
> +  static KrakenBundle fromHrefWithContent(String url, String content) {
fromHrefWithContent  看起来是 fromContent(String content, String url?), 然后 url 可选

2021-11-30 06:03 UTC, yuanyan commented on kraken/lib/src/launcher/bundle.dart
> +  static KrakenBundle fromHrefWithByteCode(String url, Uint8List bytecode) {
fromHrefWithByteCode -> fromBytecode

2021-12-03 09:35 UTC, wssgcg1213 commented on integration_tests/lib/main.dart
> +      bundle: KrakenBundle.fromWithContent('console.log("Starting integration tests...")'),
fromWithContent 应该是 fromContent

2021-12-03 09:36 UTC, wssgcg1213 commented on kraken/lib/widget.dart
> +  loadHref(KrakenBundle bundle) async {
这个不对呀, 
```
void loadBundle(KrakenBundle bundle)
```

2021-12-03 09:38 UTC, wssgcg1213 commented on kraken/lib/src/launcher/bundle.dart
> +  RawBundle.fromByteCode(Uint8List byteCode, String url)
fromBytecode 吧, 
![image](https://user-images.githubusercontent.com/3922719/144580404-41a51a3c-8b27-477c-84b0-eae6c286d6dc.png)
这个单词不是个组合词, 之前的用法就有问题

2021-12-03 09:39 UTC, wssgcg1213 commented on kraken/lib/src/launcher/bundle.dart
> +      additionalHttpHeaders?.forEach((key, value) {
additionalHttpHeaders?.forEach(request.headers.set);

2021-12-03 09:39 UTC, wssgcg1213 commented on kraken/lib/src/launcher/bundle.dart
> +  Map<String, String>? additionalHttpHeaders = {};
没有其他人用, 这个可以私有的

2021-12-03 09:39 UTC, wssgcg1213 commented on kraken/lib/src/launcher/bundle.dart
> +      additionalHttpHeaders?.forEach((key, value) {
这个 `?.` 多余了, 跟前面的判空是一个逻辑

2021-12-03 09:41 UTC, wssgcg1213 commented on kraken/lib/src/launcher/controller.dart
> +  set bundleContent(String? value) {
bundle 已经抽象掉了, 应该 set bundle(KrakenBundle bundle);

2021-12-03 09:42 UTC, wssgcg1213 commented on kraken/lib/src/launcher/launcher.dart
> +      }
你看这里的一堆判断就很恶心了, 抽象成 bundle 的目的就是消灭这些判断的, 直接 load bundle 就行了

2021-12-03 09:42 UTC, wssgcg1213 commented on kraken/lib/src/module/history.dart
> +  HistoryItem(this.href, this.state, this.needJump, { this.bundleContent, this.bundleByteCode });
this.bundle

2021-12-03 10:01 UTC, wssgcg1213 commented on kraken/lib/src/module/navigation.dart
> +    Uri sourceUri =  Uri.parse(sourceUrl);
1

2021-12-03 10:02 UTC, wssgcg1213 commented on kraken/lib/src/launcher/launcher.dart
> +  Uint8List? bundleByteCode,
1

2021-12-06 11:55 UTC, wssgcg1213 approved these changes

2021-12-07 02:42 UTC, temper357 approved these changes

2021-12-07 02:43 UTC, merged