fix: br element size
openkraken/kraken pull request #867
Opened 2021-11-10 12:45 UTC by temper357

Closes https://github.com/openkraken/kraken/issues/737

修复 BR element 高度不生效，BR element 是一个特殊的 element，设置任何 style 都不生效，同时高度只由 parent 的 line-height 决定，由于 HTML 规范中定义 BR element 实际上会被转化成一个换行符 https://www.w3.org/TR/CSS1/#br-elements ，因此 Kraken 通过渲染一个空字符串来获取换行的真实高度。

2021-11-23 06:01 UTC, yuanyan commented on kraken/lib/src/dom/element.dart
> +    if (this is BRElement) {
element不应该耦合具体 Element

2021-11-23 06:02 UTC, yuanyan commented on kraken/lib/src/rendering/flex.dart
> +    if (child is RenderBr) {
应该面向特征，不应该面向实现

2021-11-23 06:03 UTC, yuanyan commented on kraken/lib/src/rendering/br.dart
> +class RenderBr extends RenderIntrinsic {
RenderBr 命名抽象不够

2021-11-23 06:04 UTC, yuanyan commented on kraken/lib/src/rendering/box_model.dart
> +    if (this is RenderBr) {
需要面向特征，不是面向实现编码

2021-11-25 03:12 UTC, wssgcg1213 commented on kraken/lib/src/dom/element.dart
> +    if (this is BRElement) {
可以到 BRElement 的实现里里面自行监听 styleChange

2021-11-25 03:13 UTC, wssgcg1213 commented on kraken/lib/src/dom/elements/br.dart
> +class BRElement extends Element {
`BreakElement?`  like AnchorElement not AElement

2021-11-25 03:14 UTC, wssgcg1213 commented on kraken/lib/src/dom/elements/br.dart
> +  RenderBox? get renderer => renderBoxModel;
这个不需要了, 跟 Element 的实现是一样的

2021-11-25 03:15 UTC, wssgcg1213 commented on kraken/lib/src/dom/elements/br.dart
> +    if (renderer != null) {
```dart
return  _renderBr ??= RenderBr(renderStyle);
```
一行就够了

2021-11-25 03:16 UTC, wssgcg1213 commented on kraken/lib/src/rendering/box_model.dart
> +    if (this is RenderBr) {
OOM:  Override instead of judgement

2021-11-25 03:18 UTC, wssgcg1213 commented on kraken/lib/src/rendering/br.dart
> +  RenderBr(
其实这里你只需要一个高度, 不需要整个 RenderStyle 传进来, 计算可以在 Element 里做好, 这里直接用 RenderConstrainedBox 也不是不行, 传一个 tight 的 BoxConstraints 就好了

2021-11-25 03:19 UTC, wssgcg1213 requested changes
需要再改一下

2021-12-10 07:44 UTC, yuanyan commented on kraken/lib/src/rendering/br.dart
> +class RenderBr extends RenderIntrinsic {
The br element represents a line break.

While line breaks are usually represented in visual media by physically moving subsequent text to a new line, a style sheet or user agent would be equally justified in causing line breaks to be rendered in a different manner, for instance as green dots, or as extra spacing.

2021-12-10 08:16 UTC, temper357 commented on kraken/lib/src/dom/elements/br.dart
> +class BRElement extends Element {
从语义上来说 LineBreak 更完整，HTML 命名为 HTMLBRElement，感觉 follow html 保留 BRElement 更好些

2021-12-10 08:26 UTC, temper357 commented on kraken/lib/src/rendering/br.dart
> +  RenderBr(
element 对应的 RenderObject 还是用统一类型比较好，要不然 RenderLayoutBox 在 layout 时需要增加额外的类型判断

2021-12-10 08:47 UTC, temper357 commented on kraken/lib/src/rendering/br.dart
> +class RenderBr extends RenderIntrinsic {
RenderBr -> RenderLineBreak

2021-12-10 09:56 UTC, temper357 commented on kraken/lib/src/rendering/flex.dart
> +    if (child is RenderBr) {
这里做特征判断比较困难，将判断逻辑前置到 needToStretchChildCrossSize 方法中，与 RenderPositionPlaceholder 一起作为特例不允许在纵轴上 stretch。

2021-12-10 09:58 UTC, temper357 commented
浏览器对 BR element 设置 style 是生效的，也能正常读出，只是渲染不生效，因此不能使用在 bridge 侧阻断 style 指令的方式实现。

2021-12-16 06:32 UTC, wssgcg1213 commented on kraken/lib/src/rendering/line_break.dart
> +  void performLayout() {
performResize?

2021-12-16 06:33 UTC, wssgcg1213 approved these changes

2021-12-16 06:33 UTC, merged