添加 arm64 linux 支持
openkraken/kraken pull request #876
Opened 2021-11-15 06:05 UTC by suyulin

添加了linux 缺失的头文件和CLI

2021-11-15 06:20 UTC, cnryb requested changes

2021-11-15 06:20 UTC, cnryb commented on bridge/polyfill/package.json
> +    "qjsc": "git+ssh://git@gitlab.orviboserver.com:openkraken/qjsc.git#1.7",
无法访问的地址

2021-11-15 09:24 UTC, andycall commented
可以更新成 qjsc 0.2.2 版本

2021-11-16 01:28 UTC, suyulin commented on bridge/polyfill/package.json
> +    "qjsc": "git+ssh://git@gitlab.orviboserver.com:openkraken/qjsc.git#1.7",
已经更新为官方仓库

2021-11-16 04:52 UTC, andycall commented on bridge/bindings/qjs/js_context.h
> +#include <mutex>
这些头是不是不需要

2021-11-16 04:52 UTC, andycall commented on package.json
> +    "build:bridge:linux:release": "KRAKEN_BUILD=Release node scripts/build_linux",
如果是编译 Linux arm64 的话，应当是 build:bridge:linux_arm64:release

2021-11-16 04:52 UTC, andycall commented on package.json
> +    "build:bridge:linux:release": "KRAKEN_BUILD=Release node scripts/build_linux",
还少了个 debug 模式的编译配置 build:bridge:linux_arm64

2021-11-16 04:53 UTC, andycall commented on bridge/bindings/qjs/bom/performance.cc
> +#include <cmath>
这些基础库的引入添加在 js_context.h 就可以，其他的不需要再额外添加

2021-11-16 04:54 UTC, andycall commented on scripts/tasks.js
> +task('build-linux-kraken-lib', (done) => {
这里的 title 也要调整

2021-11-17 02:42 UTC, suyulin commented on scripts/tasks.js
> +task('build-linux-kraken-lib', (done) => {
已经调整

2021-11-17 02:43 UTC, suyulin commented on bridge/bindings/qjs/bom/performance.cc
> +#include <cmath>
已经添加到 js_context.h

2021-11-17 02:43 UTC, suyulin commented on package.json
> +    "build:bridge:linux:release": "KRAKEN_BUILD=Release node scripts/build_linux",
已经添加 debug，release，profile 配置

2021-11-17 03:40 UTC, andycall commented on bridge/bindings/qjs/js_context.h
> +#include <mutex>
为啥会有 mutex, locale 的使用。 kraken 的源代码中没有依赖这些功能

2021-11-17 03:55 UTC, suyulin commented on bridge/bindings/qjs/js_context.h
> +#include <mutex>
`/home/parallels/work/kraken-orvibo/bridge/include/kraken_foundation.h:150:55: error: ‘convertor’ was not declared in this scope
  150 |   std::wstring_convert<std::codecvt_utf8_utf16<T>, T> convertor;`
如果不加 locale 就会 报以上的错误。

2021-11-17 03:57 UTC, suyulin commented on bridge/bindings/qjs/js_context.h
> +#include <mutex>
编译环境可以用一个 m1 的mac 装个 ubuntu docker 就可以测试。

2021-11-18 08:47 UTC, andycall approved these changes

2021-11-18 09:14 UTC, cnryb approved these changes

2021-11-18 09:15 UTC, merged