Fix/previous blank
openkraken/kraken pull request #886
Opened 2021-11-18 11:38 UTC by answershuto

close #740

2021-11-18 12:48 UTC, yuanyan commented on kraken/lib/src/dom/text_node.dart
> +        //if previousSibling is block,should trimLeft slef.
注释格式

2021-11-18 12:55 UTC, yuanyan commented on kraken/lib/src/dom/text_node.dart
> +        //if previousSibling is block,should trimLeft slef.
当前后序节点修改了后，并不一定会触发 text 节点的更新，需要避免命令式的过程编程，放到文本layout节点去处理

2021-11-25 03:04 UTC, wssgcg1213 requested changes
.

2021-12-22 07:24 UTC, wssgcg1213 commented on kraken/lib/src/rendering/text.dart
> +  void markRenderParagraphLyout() {
拼写 typo

2021-12-22 07:24 UTC, wssgcg1213 commented on kraken/lib/src/rendering/text.dart
> +  String _collapseWhitespace(String string) {
这个方法可以 static

2021-12-22 08:18 UTC, answershuto commented on kraken/lib/src/rendering/text.dart
> +  String _collapseWhitespace(String string) {
已修改

2021-12-23 03:06 UTC, wssgcg1213 approved these changes

2021-12-23 06:32 UTC, temper357 commented on kraken/lib/src/css/display.dart
> +      if (renderBoxModel?.parent != null && renderBoxModel?.parent is RenderFlowLayout && renderBoxModel?.parentData is RenderLayoutParentData) {
这里已经判断了 parent 是否为 RenderFlowLayout，不需要重复判断 parentData 是否为 RenderLayoutParentData 了

2021-12-23 06:33 UTC, temper357 commented on kraken/lib/src/css/display.dart
> +        RenderLayoutParentData childParentData = renderBoxModel?.parentData as RenderLayoutParentData;
从语义上来讲直接用 parentData 命名好了，childParentData 感觉是当前 renderBoxModel 的 child

2021-12-23 06:38 UTC, temper357 commented on kraken/lib/src/css/position.dart
> +    if (renderBoxModel?.parent != null && renderBoxModel?.parent is RenderFlowLayout && renderBoxModel?.parentData is RenderLayoutParentData) {
这段给 textNode 标识的 needsLayout 的逻辑是通用的，可以抽离到 renderBoxModel 中

2021-12-23 06:44 UTC, temper357 commented on kraken/lib/src/rendering/text.dart
> +  String get data {
这个 data 应该只会给 _renderParagraph 内部使用不对外暴露，建议与 originData 对调一下，originData 改成 data，这个 data 改成辟如 _trimmedData 的私有变量

2021-12-23 07:04 UTC, temper357 commented on kraken/lib/src/dom/node.dart
> +    if (parentNode != null && parentNode?.renderer is RenderFlowLayout && renderer?.parentData is RenderLayoutParentData) {
这里也可以复用公共的 markAdjacentRenderParagraphNeedsLayout

2021-12-23 07:39 UTC, temper357 approved these changes

2021-12-23 07:43 UTC, wssgcg1213 approved these changes

2021-12-23 07:44 UTC, merged