[WIP] refactor: layout performance
openkraken/kraken pull request #897
Opened 2021-11-23 03:05 UTC by temper357

* 重构 layout constraints 逻辑，通过在 renderStyle 中缓存 logical width/height，内层 renderBoxModel 直接使用 parent 的 logical width/height，避免一直向上递归的性能损耗，可以提升诸如多层 flex 容器嵌套且每层未指定 width 场景下 layout 性能。

2021-11-25 07:27 UTC, andycall commented
需要结合这个 PR https://github.com/openkraken/kraken/pull/890 编写有关性能优化场景的测试用例，将理论上的优化通过测试沉淀下来。毕竟后续更改有可能会 break 掉优化

2021-11-25 07:27 UTC, andycall requested changes
需要编写 profile 测试

2021-11-25 09:36 UTC, yuanyan commented
应该是把样式放到 dart 侧来生效，这样才是区别才只剩下传输

2021-11-25 09:41 UTC, yuanyan commented on kraken/lib/src/css/values/length.dart
> +    return !isAuto;
这个优化从性能角度是下降了，并且两个方法形成了依赖

2021-11-25 12:46 UTC, temper357 commented on kraken/lib/src/css/values/length.dart
> +    return !isAuto;
这里属于 Bug fix，因为 isAuto 的 getter 里加了百分比的判断逻辑并不是单单判断 type 等于 AUTO ，因此 isNotAuto 里需要加上 isAuto 的相反判断逻辑，如果不希望两个方法形成依赖，可以将判断逻辑抽成一个单独方法在两个 getter 中分别调用。

2021-11-26 05:53 UTC, yuanyan approved these changes

2021-11-26 06:00 UTC, yuanyan commented
> 需要结合这个 PR #878 编写有关性能优化场景的测试用例，将理论上的优化通过测试沉淀下来。毕竟后续更改有可能会 break 掉优化

我们需要先建立起性能beachmark建立起基线，这块 @wssgcg1213 回在 github actions上建立一套

2021-12-06 13:39 UTC, yuanyan approved these changes

2021-12-07 06:56 UTC, andycall approved these changes

2021-12-07 06:56 UTC, merged