[WIP]Feat/support flutter widget
openkraken/kraken pull request #904
Opened 2021-11-24 15:05 UTC by answershuto

支持 Flutter Widget 与 Element 混合渲染，互相嵌套。

2021-11-25 09:19 UTC, andycall commented
Design Graph:

![kraken](https://user-images.githubusercontent.com/4409743/143413850-38c4830e-4ed2-4d59-85c3-0d4c059a52ab.png)

2021-11-25 10:53 UTC, yuanyan commented on kraken/lib/widget.dart
> +export 'src/widgets/kraken.dart';
目录名风格统一：widgets -> widget

2021-11-25 10:54 UTC, yuanyan commented on kraken/lib/src/launcher/controller.dart
> +  late RenderObjectElement rootKrakenElement;
KrakenElement 命名上有歧义

2021-11-25 12:22 UTC, andycall commented on kraken/lib/src/launcher/controller.dart
> +  late RenderObjectElement rootKrakenElement;
这个是由 Kraken Widget 创建的 Element，而不是由 Flutter Framwork创建的。 所以叫 rootKrakenElement

2021-11-25 12:25 UTC, andycall commented on kraken/lib/widget.dart
> +export 'src/widgets/kraken.dart';
flutter 那边也是 widgets  

https://github.com/flutter/flutter/tree/master/packages/flutter/lib/src/widgets

2021-11-26 02:52 UTC, answershuto commented on kraken/lib/widget.dart
> +export 'src/widgets/kraken.dart';
flutter 那边的概念跟我们不太一样，他们的目录下是一堆 widgets，我们是桥接 widget 的能力，我改过来。

2021-11-26 12:18 UTC, haikyuu commented
This isn't related to HTML custom elements right?

2021-11-29 05:56 UTC, answershuto commented
> This isn't related to HTML custom elements right?

This PR provides a way to make the Flutter Widget use as custom elements.

2021-12-01 06:40 UTC, answershuto commented
目前结构以及生命周期支持 Kraken Element 与 Flutter Widget 的混合渲染，以下 Demo 包含下面几种情况。

+ [x] Element 作为 Container 下 append 一层 Flutter Widget。
+ [x] Flutter Widget 作为 Container 下 append Element。
+ [x] Flutter Widget 作为 Container 下 append  Flutter Widget。
+ [x] Flutter Widget 作为 Container 下 append  Element 作为子 Container，  Element 继续 append Flutter Widget 。
+ [x] Element 作为 Container 下 append Element。


```js
var text1 = document.createTextNode('Hello World!');
var br = document.createElement('br');
var text2 = document.createTextNode('你好，世界！');
var c = document.createElement('p');
c.style.textAlign = 'center';
c.appendChild(text1);
c.appendChild(br);
c.appendChild(text2);

document.body.appendChild(c);


const divContainer = document.createElement('div');
divContainer.style.width = '300px';
divContainer.style.height = '500px';
divContainer.style.backgroundColor = 'green';
divContainer.style.border = '10px solid black';
divContainer.appendChild(document.createTextNode('div container'));

document.body.appendChild(divContainer);

const flutterContainer = document.createElement('flutter-container');
divContainer.appendChild(flutterContainer);



const p = document.createElement('p');
p.style.width = '100px';
p.style.height = '100px';
p.style.backgroundColor = 'blue';
p.style.border = '3px solid yellow';
p.appendChild(document.createTextNode('p child'))

const div = document.createElement('div');
div.style.width = '100px';
div.style.height = '100px';
div.style.backgroundColor = 'blue';
div.appendChild(document.createTextNode('div child'))


const flutterChiild = document.createElement('flutter-child');
flutterContainer.appendChild(flutterChiild);

flutterContainer.appendChild(p);
flutterContainer.appendChild(div);
flutterContainer.appendChild(document.createTextNode('666'));

const flutterText = document.createElement('flutter-text');
div.appendChild(flutterText)
```

```dart
class ContainerWidgetElement extends WidgetElement {
  ContainerWidgetElement(int targetId, Pointer<NativeEventTarget> nativeEventTarget, ElementManager elementManager) :
        super(targetId, nativeEventTarget, elementManager);

  @override
  Widget build(BuildContext context, Map<String, dynamic> properties, List<Widget> children) {

    List<Widget> list = [];
    list.addAll([
      Text('Flutter Container', textDirection: TextDirection.ltr, style: TextStyle(color: Colors.red)),
    ]);
    list.addAll(children);

    return Container(
      width: 200,
      height: 200,
      decoration: const BoxDecoration(
        border: Border( top: BorderSide( width: 5, color: Colors.red ), bottom: BorderSide( width: 5, color: Colors.red ), left: BorderSide( width: 5, color: Colors.red ), right: BorderSide( width: 5, color: Colors.red )),
      ),
      child: Column(
        children: list,
      ),
    );
  }
}

class ShowWidgetElement extends WidgetElement {
  ShowWidgetElement(int targetId, Pointer<NativeEventTarget> nativeEventTarget, ElementManager elementManager) :
        super(targetId, nativeEventTarget, elementManager);

  @override
  Widget build(BuildContext context, Map<String, dynamic> properties, List<Widget> children) {
    return Text('child show flutter widget', textDirection: TextDirection.ltr, style: TextStyle(color: Color.fromARGB(255, 200, 10, 5)));
  }
}

class TextWidgetElement extends WidgetElement {
  TextWidgetElement(int targetId, Pointer<NativeEventTarget> nativeEventTarget, ElementManager elementManager) :
        super(targetId, nativeEventTarget, elementManager);

  @override
  Widget build(BuildContext context, Map<String, dynamic> properties, List<Widget> children) {
    return Text('flutter text widget', textDirection: TextDirection.ltr, style: TextStyle(color: Color.fromARGB(255, 200, 50, 100)));
  }
}

void defineKrakenCustomElements() {
  Kraken.defineCustomElement('flutter-container', (targetId, nativeEventTarget, elementManager) {
    return ContainerWidgetElement(targetId, nativeEventTarget, elementManager);
  });

  Kraken.defineCustomElement('flutter-child', (targetId, nativeEventTarget, elementManager) {
    return ShowWidgetElement(targetId, nativeEventTarget, elementManager);
  });

  Kraken.defineCustomElement('flutter-text', (targetId, nativeEventTarget, elementManager) {
    return TextWidgetElement(targetId, nativeEventTarget, elementManager);
  });
}
```

![image](https://user-images.githubusercontent.com/17812136/144184009-315834f0-d429-4c68-8076-256894a84e40.png)

2021-12-02 11:42 UTC, wssgcg1213 commented on kraken/lib/src/widget/kraken.dart
> +        child: FocusableActionDetector(
缩进不对

2021-12-03 08:21 UTC, yuanyan commented on kraken/lib/src/launcher/controller.dart
> +  late RenderObjectElement rootKrakenElement;
不是谁创建，是创建了什么

2021-12-03 12:03 UTC, andycall commented on kraken/lib/src/launcher/controller.dart
> +  late RenderObjectElement rootKrakenElement;
https://github.com/openkraken/kraken/blob/feat%2Fsupport_flutter_widget/kraken/lib/src/widget/kraken.dart#L876

2021-12-03 12:05 UTC, andycall commented
这个搞完之后，Gallery 应当也用 Flutter Widget 写个复杂一点的 demo

2021-12-07 02:52 UTC, answershuto commented
使用 widget scroll 容器 [waterfall_flow](https://pub.dev/packages/waterfall_flow) 渲染 10000 个节点的例子。

![image](https://user-images.githubusercontent.com/17812136/144957438-26ec77bd-6b50-42ce-bf97-d92d023c5250.png)


```dart

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:kraken/kraken.dart';
import 'package:kraken_websocket/kraken_websocket.dart';
import 'dart:ui';
import 'package:kraken/widget.dart';
import 'package:kraken/dom.dart';
import 'dart:ffi';
import 'package:waterfall_flow/waterfall_flow.dart';

void main() {
  KrakenWebsocket.initialize();
  runApp(MyApp());
  defineKrakenCustomElements();
}

class FlutterContainerWidgetElement extends WidgetElement {
  FlutterContainerWidgetElement(int targetId, Pointer<NativeEventTarget> nativeEventTarget, ElementManager elementManager) :
        super(targetId, nativeEventTarget, elementManager);

  List<Widget> _children = [];

  Widget _func (BuildContext context, int index) {
    if (index < _children.length) {
      return _children[index];
    } else {
      return Text('data');
    }
  }

  @override
  Widget build(BuildContext context, Map<String, dynamic> properties, List<Widget> children) {
    _children = children;

    return WaterfallFlow.builder(
      //cacheExtent: 0.0,
      itemBuilder: _func,
      padding: EdgeInsets.all(5.0),
      gridDelegate: SliverWaterfallFlowDelegateWithFixedCrossAxisCount(
        crossAxisCount: 2,
        crossAxisSpacing: 5.0,
        mainAxisSpacing: 5.0,
        lastChildLayoutTypeBuilder: (index) => index == children.length
            ? LastChildLayoutType.foot
            : LastChildLayoutType.none,
      ),
    );
  }
}

class ContainerWidgetElement extends WidgetElement {
  ContainerWidgetElement(int targetId, Pointer<NativeEventTarget> nativeEventTarget, ElementManager elementManager) :
        super(targetId, nativeEventTarget, elementManager);

  @override
  Widget build(BuildContext context, Map<String, dynamic> properties, List<Widget> children) {

    List<Widget> list = [];
    list.addAll([
      Text('Flutter Container', textDirection: TextDirection.ltr, style: TextStyle(color: Colors.red)),
    ]);
    list.addAll(children);

    return Container(
      width: 200,
      height: 200,
      decoration: const BoxDecoration(
        border: Border( top: BorderSide( width: 5, color: Colors.red ), bottom: BorderSide( width: 5, color: Colors.red ), left: BorderSide( width: 5, color: Colors.red ), right: BorderSide( width: 5, color: Colors.red )),
      ),
      child: Column(
        children: list,
      ),
    );
  }
}

class ShowWidgetElement extends WidgetElement {
  ShowWidgetElement(int targetId, Pointer<NativeEventTarget> nativeEventTarget, ElementManager elementManager) :
        super(targetId, nativeEventTarget, elementManager);

  @override
  Widget build(BuildContext context, Map<String, dynamic> properties, List<Widget> children) {
    return Text('child show flutter widget', textDirection: TextDirection.ltr, style: TextStyle(color: Color.fromARGB(255, 200, 10, 5)));
  }
}

class TextWidgetElement extends WidgetElement {
  TextWidgetElement(int targetId, Pointer<NativeEventTarget> nativeEventTarget, ElementManager elementManager) :
        super(targetId, nativeEventTarget, elementManager);

  @override
  Widget build(BuildContext context, Map<String, dynamic> properties, List<Widget> children) {
    return Text('flutter text widget', textDirection: TextDirection.ltr, style: TextStyle(color: Color.fromARGB(255, 200, 50, 100)));
  }
}

void defineKrakenCustomElements() {
  Kraken.defineCustomElement('f-container', (targetId, nativeEventTarget, elementManager) {
    return ContainerWidgetElement(targetId, nativeEventTarget, elementManager);
  });

  Kraken.defineCustomElement('flutter-container', (targetId, nativeEventTarget, elementManager) {
    return FlutterContainerWidgetElement(targetId, nativeEventTarget, elementManager);
  });

  Kraken.defineCustomElement('flutter-child', (targetId, nativeEventTarget, elementManager) {
    return ShowWidgetElement(targetId, nativeEventTarget, elementManager);
  });

  Kraken.defineCustomElement('flutter-text', (targetId, nativeEventTarget, elementManager) {
    return TextWidgetElement(targetId, nativeEventTarget, elementManager);
  });
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Kraken Browser',
      // theme: ThemeData.dark(),
      home: MyBrowser(),
    );
  }
}

class MyBrowser extends StatefulWidget {
  MyBrowser({Key? key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String? title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

Widget aaa (BuildContext context, int index) {
  return Text('aaa');
  // return _children[index];
}

class _MyHomePageState extends State<MyBrowser> {

  OutlineInputBorder outlineBorder = OutlineInputBorder(
    borderSide: BorderSide(color: Colors.transparent, width: 0.0),
    borderRadius: const BorderRadius.all(
      Radius.circular(20.0),
    ),
  );

  @override
  Widget build(BuildContext context) {
    final MediaQueryData queryData = MediaQuery.of(context);
    final TextEditingController textEditingController = TextEditingController();

    List<int> _list = [];

    Kraken? _kraken;
    AppBar appBar = AppBar(
      backgroundColor: Colors.black87,
      titleSpacing: 10.0,
      title: Container(
        height: 40.0,
        child: TextField(
          controller: textEditingController,
          onSubmitted: (value) {
            textEditingController.text = value;
            _kraken?.loadURL(value);
          },
          decoration: InputDecoration(
            hintText: 'Enter a app url',
            hintStyle: TextStyle(color: Colors.black54, fontSize: 16.0),
            contentPadding: const EdgeInsets.all(10.0),
            filled: true,
            fillColor: Colors.grey,
            border: outlineBorder,
            focusedBorder: outlineBorder,
            enabledBorder: outlineBorder,
          ),
          style: TextStyle(color: Colors.black, fontSize: 16.0),
        ),
      ),
      // Here we take the value from the MyHomePage object that was created by
      // the App.build method, and use it to set our appbar title.
    );

    final Size viewportSize = queryData.size;
    return Scaffold(
        appBar: appBar,
        body: Center(
          // Center is a layout widget. It takes a single child and positions it
          // in the middle of the parent.
          child: _kraken = Kraken(
            viewportWidth: viewportSize.width - queryData.padding.horizontal,
            viewportHeight: viewportSize.height - appBar.preferredSize.height - queryData.padding.vertical,
            bundleURL: 'http://127.0.0.1:3300/kraken_debug_server.js',
          ),
        )
    );
  }
}


```

```js



const flutterContainer = document.createElement('flutter-container');
flutterContainer.style.height = '100vh';
flutterContainer.style.display = 'block';
document.body.appendChild(flutterContainer);

const colors = ['red', 'yellow', 'black', 'blue', 'green'];
const images = [
    'https://img.alicdn.com/imgextra/i1/O1CN01OPE9Pw1yFUVfLc82O_!!6000000006549-2-tps-325-289.png',
    'https://img.alicdn.com/imgextra/i4/O1CN01Edx8Jk1ELTLfISD7H_!!6000000000335-2-tps-1000-1000.png',
    'https://img.alicdn.com/imgextra/i3/O1CN015bPNOp1cG1OJ5T6pT_!!6000000003572-0-tps-1919-1080.jpg',
    'https://img.alicdn.com/im [...]

2021-12-17 11:59 UTC, yuanyan commented
> haikyuu

Not web components，web components will support in future.

2021-12-20 11:21 UTC, wssgcg1213 approved these changes

2021-12-20 16:48 UTC, andycall commented on kraken/lib/src/widget/kraken.dart
> +    // FIXME: reset href when dart hot reload that href is prev href
这里我记得在那个 PR 删掉了

2021-12-20 16:54 UTC, andycall requested changes
一些优化需要调整。貌似 main 上 widget.dart 没有同步过来，需要手动 check 一下

2021-12-21 06:35 UTC, answershuto commented on kraken/lib/src/widget/widget_to_element_adaptor.dart
> +        return state.build(context);
这里子节点会调用 WidgetElement 上的 build 方法，该方法也许会依赖父节点的信息做一些转换，重新 build 把优化的权利交给开发者，这里不缓存防止需要重新 build 的时候不执行。KrakenElementToWidgetAdaptor 我加上缓存。

2021-12-21 06:50 UTC, andycall approved these changes

2021-12-21 06:52 UTC, wssgcg1213 approved these changes

2021-12-21 06:53 UTC, merged