feat: add test case and implentation for HTMLElement#firstElementChil…
openkraken/kraken pull request #924
Opened 2021-11-29 09:35 UTC by wssgcg1213

Close #923

2021-11-29 09:48 UTC, answershuto requested changes

2021-11-29 09:48 UTC, answershuto commented on bridge/bindings/qjs/dom/element.cc
> +PROP_SETTER(ElementInstance, firstElementChild)(QjsContext* ctx, JSValue this_val, int argc, JSValue* argv) {
空行

2021-11-29 09:48 UTC, answershuto commented on bridge/bindings/qjs/dom/element.cc
> +PROP_SETTER(ElementInstance, lastElementChild)(QjsContext* ctx, JSValue this_val, int argc, JSValue* argv) {
1

2021-11-29 11:19 UTC, wssgcg1213 commented on bridge/bindings/qjs/dom/element.cc
> +PROP_SETTER(ElementInstance, firstElementChild)(QjsContext* ctx, JSValue this_val, int argc, JSValue* argv) {
啥意思, 要空一行?

2021-11-29 11:21 UTC, wssgcg1213 commented on bridge/bindings/qjs/dom/element.cc
> +PROP_SETTER(ElementInstance, firstElementChild)(QjsContext* ctx, JSValue this_val, int argc, JSValue* argv) {
上面不空行我是参考前面的写法的, 如果需要修改的话先确认一下风格 
![image](https://user-images.githubusercontent.com/3922719/143859183-89b7fbd1-cdc9-4c29-86d6-7d7a46655199.png)

2021-11-29 11:23 UTC, answershuto approved these changes

2021-11-30 03:26 UTC, yuanyan approved these changes

2021-11-30 03:27 UTC, merged