fix: paint order of fixed element
openkraken/kraken pull request #960
Opened 2021-12-09 11:34 UTC by temper357

目前 position 定位的实现是将 renderObject 的真实节点移动到 containing block element 底下，因此 renderObject tree 的结构不能与 element tree 结构一一映射，会导致 parent 的 renderObject depth 可能会小于 child 对应的 depth，因此判断 position 为 fixed element 的渲染优先级不应该 renderObject tree 结构，而应使用与 element tree 结构相同的 renderStyle tree。

2021-12-09 14:24 UTC, yuanyan commented on kraken/lib/src/css/render_style.dart
> +  bool isAncestorForChild(RenderStyle childRenderStyle) {
isAncestorForChild 命名上需要更清晰易懂些

2021-12-09 14:25 UTC, yuanyan commented on kraken/lib/src/css/render_style.dart
> +  bool isAncestorForChild(RenderStyle childRenderStyle) {
isAncestorOf

2021-12-10 07:36 UTC, yuanyan approved these changes

2021-12-13 07:41 UTC, andycall approved these changes

2021-12-13 07:41 UTC, andycall commented
没有测试用例

2021-12-13 07:42 UTC, andycall requested changes
没有测试用例

2021-12-15 05:25 UTC, yuanyan approved these changes

2021-12-15 05:25 UTC, andycall approved these changes

2021-12-15 05:26 UTC, merged