feat: add css variables and support link element
openkraken/kraken pull request #961
Opened 2021-12-09 11:45 UTC by wssgcg1213

1. Support LinkElement with rel equals `stylesheet` will send request and parse style. Close #955 
2. Support ScriptElement with type equals `application/javascript` and `application/x-javascript`, since `text/javascript` is an obsolete mime.
3. Support CSSVariables Close #480 
4. Fix UICommand `id` and `type` is a signed int, which was cast to unsigned causing not working in newly version of Flutter.

2021-12-10 03:55 UTC, answershuto commented on kraken/lib/src/launcher/bundle.dart
> -  Future<KrakenBundle> resolve(int contextId) async {
这个为啥要加？呀

2021-12-10 03:55 UTC, answershuto commented on kraken/lib/src/css/variable.dart
> + * Copyright (C) 2019-present Alibaba Inc. All rights reserved.
2021年了

2021-12-10 03:55 UTC, answershuto commented on kraken/lib/src/launcher/bundle.dart
> -  Future<void> resolve(int contextId) async {
同

2021-12-10 07:20 UTC, wssgcg1213 commented on kraken/lib/src/launcher/bundle.dart
> -  Future<KrakenBundle> resolve(int contextId) async {
去耦合, 跟 EventTargetContext 是 nullable 的原因一样, KrakenBundle 可以单独测试, contextId 的依赖本质上是依赖 Bridge (这个 id 是 bridge 生成的)

2021-12-10 07:34 UTC, yuanyan commented on kraken/lib/src/dom/elements/head.dart
> +  void setProperty(String key, dynamic value) {
需要补充下测试用例

2021-12-10 07:35 UTC, yuanyan commented on kraken/lib/src/dom/element.dart
> +      default:
需要补充对应测试用例，尤其是更新 var 的测试

2021-12-10 10:45 UTC, wssgcg1213 commented on kraken/lib/src/dom/element.dart
> +      default:
ok, Doing

2021-12-10 13:27 UTC, answershuto requested changes

2021-12-10 13:27 UTC, answershuto commented on kraken/lib/src/launcher/bundle.dart
> -  Future<void> eval(int contextId) async {
如果 eval 去掉了contextId 的 耦合的话，我理解 KrakenBundle 应该是一个抽象类，在上面派生出 ，eval 的职责应该丢给 contraoller，然后 controller 提供一个 eval(BundleKraken bundle) 的方法。

2021-12-13 07:50 UTC, wssgcg1213 commented on kraken/lib/src/launcher/bundle.dart
> -  Future<void> eval(int contextId) async {
是的, KrakenBundle 作为抽象类会好一点

2021-12-13 07:51 UTC, wssgcg1213 commented on kraken/lib/src/launcher/bundle.dart
> -  Future<void> eval(int contextId) async {
这里暂时先不改了, 只是为了解决 contextId Nullable 传染性的问题才改了参数声明, 后面单独重构一个 PR 好了

2021-12-13 11:57 UTC, wssgcg1213 commented
增加了依赖收集, 同时解决了样式继承的 CSSVar 更新的问题.   

背景色的测试用例还有一些问题, 整体思路可以先 Review 一下

2021-12-14 07:42 UTC, temper357 commented on kraken/lib/src/css/render_style.dart
> +  void visitChildren<T extends RenderStyle>(RenderStyleVisitor<T> visitor) {
这里通过 element 去取 renderStyle children 职责有点不清晰，是不是考虑实现完整的 renderStyle tree，直接遍历 renderStyle tree 就好了

2021-12-15 07:20 UTC, wssgcg1213 commented on kraken/lib/src/css/render_style.dart
> +  void visitChildren<T extends RenderStyle>(RenderStyleVisitor<T> visitor) {
是的, 如果有直接的 RenderStyle 树状结构, 就不需要这么去干了    
目前没有, 整一个的话成本还有点高, 所以为了结构清晰我先把这个方法抽出来了, 未来实现好了之后改这里就好了

2021-12-15 15:16 UTC, yuanyan commented on kraken/lib/src/css/render_style.dart
> +    // Transition
格式对齐

2021-12-15 15:16 UTC, yuanyan commented on kraken/lib/src/css/render_style.dart
> +    if (CSSVariableMixin.isVariable(propertyName)) {
css 变量是少数情况，应该把逻辑放到多数情况判断后面

2021-12-15 15:24 UTC, yuanyan commented on kraken/lib/src/css/variable.dart
> +  static bool isVariable(String? value) {
这个静态方法可以放到 kraken/lib/src/css/values/variable.dart 里

2021-12-16 05:27 UTC, yuanyan commented on kraken/lib/src/css/render_style.dart
> +    if (CSSFunction.isFunction(propertyValue, functionName: 'var')) {
这里的逻辑移到 CSSVariableMixin 里更内聚些

2021-12-16 05:38 UTC, yuanyan commented on kraken/lib/src/css/values/function.dart
> +    bool isMatch = _functionRegExp.hasMatch(value);
可以优化下性能

2021-12-16 09:24 UTC, temper357 approved these changes

2021-12-16 09:27 UTC, andycall approved these changes

2021-12-16 09:31 UTC, answershuto approved these changes

2021-12-16 09:31 UTC, merged